function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var d=[];!(b=a.next()).done;)d.push(b.value);a=d}return a}zzfx=function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];return zzfxP(zzfxG.apply(null,ba(b)))};
zzfxP=function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];d=zzfxX.createBufferSource();var h=zzfxX.createBuffer(b.length,b[0].length,zzfxR);b.map(function(e,p){return h.getChannelData(p).set(e)});d.buffer=h;d.connect(zzfxX.destination);return d};
zzfxG=function(a,b,d,h,e,p,u,l,k,T,da,ra,Ca,fa,na,sa,La,ta,gb,P,ea,ua,va,ja,Y,U,wa,ha,Ta,hb,vb,ib,jb,R,kb,lb,V,Da,Ua){a=void 0===a?1:a;b=void 0===b?.05:b;d=void 0===d?220:d;u=void 0===u?0:u;l=void 0===l?1:l;k=void 0===k?0:k;T=void 0===T?0:T;da=void 0===da?0:da;ra=void 0===ra?0:ra;Ca=void 0===Ca?0:Ca;fa=void 0===fa?0:fa;na=void 0===na?0:na;sa=void 0===sa?0:sa;ta=void 0===ta?1:ta;P=void 0===P?zzfxR:P;ea=void 0===ea?99+(void 0===h?0:h)*P:ea;ua=void 0===ua?(void 0===e?0:e)*P:ua;va=void 0===va?(void 0===
p?.1:p)*P:va;ja=void 0===ja?(void 0===gb?0:gb)*P:ja;Y=void 0===Y?(void 0===La?0:La)*P:Y;U=void 0===U?2*Math.PI:U;wa=void 0===wa?function(cc){return 0<cc?1:-1}:wa;ha=void 0===ha?ea+ja+ua+va+Y:ha;Ta=void 0===Ta?k*=500*U/Math.pow(P,2):Ta;hb=void 0===hb?d*=(1+2*b*Math.random()-b)*U/P:hb;vb=void 0===vb?wa(na)*U/4:vb;ib=void 0===ib?0:ib;jb=void 0===jb?0:jb;R=void 0===R?0:R;kb=void 0===kb?0:kb;lb=void 0===lb?0:lb;V=void 0===V?0:V;Da=void 0===Da?1:Da;for(Ua=void 0===Ua?[]:Ua;R<ha;Ua[R++]=V)++lb>100*sa&&(lb=
0,V=ib*d*Math.sin(jb*na*U/P-vb),V=wa(V=u?1<u?2<u?3<u?Math.sin(Math.pow(V%U,3)):Math.max(Math.min(Math.tan(V),1),-1):1-(2*V/U%2+2)%2:1-4*Math.abs(Math.round(V/U)-V/U):Math.sin(V))*Math.pow(Math.abs(V),l)*a*zzfxV*(R<ea?R/ea:R<ea+ja?1-(R-ea)/ja*(1-ta):R<ea+ja+ua?ta:R<ha-Y?(ha-R-Y)/va*ta:0),V=Y?V/2+(Y>R?0:(R<ha-Y?1:(R-ha)/Y)*Ua[R-Y|0]/2):V),ib+=1-fa+1E9*(Math.sin(R)+1)%2*fa,jb+=1-fa+1E9*(Math.pow(Math.sin(R),2)+1)%2*fa,d+=k+=500*T*U/Math.pow(P,3),Da&&++Da>ra*P&&(d+=da*U/P,hb+=da*U/P,Da=0),Ca&&++kb>Ca*
P&&(d=hb,k=Ta,kb=1,Da=Da||1);return Ua};zzfxV=.5;zzfxR=44100;zzfxX=new (top.AudioContext||webkitAudioContext);
zzfxM=function(a,b,d,h){for(var e,p,u,l,k,T,da,ra,Ca,fa,na,sa,La,ta,gb=0,P=[],ea=[],ua=[],va=0,ja=0,Y=1,U={},wa=zzfxR/(void 0===h?125:h)*60>>2;Y;va++)P=[Y=ra=sa=0],d.map(function(ha,Ta){da=b[ha][va]||[0,0,0];Y|=!!b[ha][va];ta=sa+(b[ha][0].length-2-!ra)*wa;La=Ta==d.length-1;p=2;for(l=sa;p<da.length+La;ra=++p){k=da[p];Ca=p==da.length+La-1&&La||fa!=(da[0]||0)|k|0;for(u=0;u<wa&&ra;u++>wa-99&&Ca?na+=(1>na)/99:0)T=(1-na)*P[gb++]/2||0,ea[l]=(ea[l]||0)-T*ja+T,ua[l]=(ua[l++]||0)+T*ja+T;k&&(na=k%1,ja=da[1]||
0,(k|=0)&&(P=U[[fa=da[gb=0]||0,k]]=U[[fa,k]]||(e=[].concat(ba(a[fa])),e[2]*=Math.pow(2,(k-12)/12),0<k?zzfxG.apply(null,ba(e)):[])))}sa=ta});return[ea,ua]};var ca=Array.from(Array(18).keys()).map(function(a){return 2==a?15:0}),ia=ca.slice();ia[14]=15;var ka=Array.from(Array(18).keys()).map(function(a){return 10==a?15:0==a?1:0}),la=Array.from(Array(18).keys()).map(function(a){return 0==a?2:0==a%4&&12!=a?15:0});
function ma(a){return Array.from(Array(18).keys()).map(function(b){return 0==b?3:[2,6,10,14].includes(b)?a+[.1,.5,.7][[2,6,10,14].indexOf(b)]:1==b?-.1:0})}
var oa=ma(18),pa=ma(22),qa=ma(24),xa=ma(30),ya=[8,9,10,11,8,9,10,11],za=[[[,0,86,,,,,.7,,,,.5,,6.7,1,.05],[.7,0,270,,,.12,3,1.65,-2,,,,,4.5,,.02],[.4,0,2200,,,.04,3,2,,,800,.02,,4.8,,.01,.1],[,0,130.81,,,1]],[[oa],[pa],[qa],[xa],[oa,ca,ka],[pa,ca,ka],[qa,ca,ka],[xa,ia,ka],[oa,ca,ka,la],[pa,ca,ka,la],[qa,ca,ka,la],[xa,ia,ka,la]],[0,1,2,3,0,1,2,3,4,5,6,7,4,5,6,7].concat(ya).concat(ya).concat(ya).concat(ya),120,{title:"",aa:""}];function Aa(a,b,d){this.x=a;this.y=b;this.z=d}
function Ba(a,b,d){return a.x*b+a.y*d}
var Ea=[new Aa(1,1,0),new Aa(-1,1,0),new Aa(1,-1,0),new Aa(-1,-1,0),new Aa(1,0,1),new Aa(-1,0,1),new Aa(1,0,-1),new Aa(-1,0,-1),new Aa(0,1,1),new Aa(0,-1,1),new Aa(0,1,-1),new Aa(0,-1,-1)],Fa=[151,160,137,91,90,15,131,13,201,95,96,53,194,233,7,225,140,36,103,30,69,142,8,99,37,240,21,10,23,190,6,148,247,120,234,75,0,26,197,62,94,252,219,203,117,35,11,32,57,177,33,88,237,149,56,87,174,20,125,136,171,168,68,175,74,165,71,134,139,48,27,166,77,146,158,231,83,111,229,122,60,211,133,230,220,105,92,41,55,
46,245,40,244,102,143,54,65,25,63,161,1,216,80,73,209,76,132,187,208,89,18,169,200,196,135,130,116,188,159,86,164,100,109,198,173,186,3,64,52,217,226,250,124,123,5,202,38,147,118,126,255,82,85,212,207,206,59,227,47,16,58,17,182,189,28,42,223,183,170,213,119,248,152,2,44,154,163,70,221,153,101,155,167,43,172,9,129,22,39,253,19,98,108,110,79,113,224,232,178,185,112,104,218,246,97,228,251,34,242,193,238,210,144,12,191,179,162,241,81,51,145,235,249,14,239,107,49,192,214,31,181,199,106,157,184,84,204,
176,115,121,50,45,127,4,150,254,138,236,205,93,222,114,67,29,24,72,243,141,128,195,78,66,215,61,156,180],Ga=Array(512),Ha=Array(512);function Ia(a){0<a&&1>a&&(a*=65536);a=Math.floor(a);256>a&&(a|=a<<8);for(var b=0;256>b;b++){var d=b&1?Fa[b]^a&255:Fa[b]^a>>8&255;Ga[b]=Ga[b+256]=d;Ha[b]=Ha[b+256]=Ea[d%12]}}Ia(0);function Ja(a,b,d){return(1-d)*a+d*b}
function Ka(a,b){var d=Math.floor(a),h=Math.floor(b);a-=d;b-=h;d&=255;h&=255;var e=a*a*a*(a*(6*a-15)+10);return Ja(Ja(Ba(Ha[d+Ga[h]],a,b),Ba(Ha[d+1+Ga[h]],a-1,b),e),Ja(Ba(Ha[d+Ga[h+1]],a,b-1),Ba(Ha[d+1+Ga[h+1]],a-1,b-1),e),b*b*b*(b*(6*b-15)+10))}function Ma(a,b,d){this.x=a;this.y=b;this.$=d;this.f=!1;this.i={type:"NONE"};this.a={type:"NONE"};this.isVisible=this.highlighted=!1;this.o={x:0,y:0};this.C=0}function Na(a,b,d,h){this.r=a;this.U=b;this.S=d;this.Y=h}
function Oa(a){return"#"+Pa(a.r)+Pa(a.U)+Pa(a.S)+Pa(a.Y)}function Qa(a,b){return new Na(Math.min(255,Math.trunc(a.r*b)),Math.min(255,Math.trunc(a.U*b)),Math.min(255,Math.trunc(a.S*b)),a.Y)}var Ra=document.getElementById("canv"),c=Ra.getContext("2d");c.imageSmoothingEnabled=!1;var f=[],g=[],Sa=[{x:1,y:0},{x:.5,y:.866025},{x:-.5,y:.866025},{x:-1,y:0},{x:-.5,y:-.866025},{x:.5,y:-.866025}],m=1,Va=new Map;Va.set("ROCK",new Na(100,100,100,255));Va.set("IRON",new Na(165,42,42,255));
Va.set("COPPER",new Na(184,115,51,255));Va.set("CARBON",new Na(18,18,18,255));Va.set("LITHIUM",new Na(169,169,169,255));Va.set("SILICON",new Na(0,153,204,255));Va.set("PLUTONIUM",new Na(0,255,0,255));var n=document.getElementById("rover"),Wa=new Map;Wa.set("RADAR",document.getElementById("tower"));Wa.set("CONSTRUCTOR",document.getElementById("constructor"));Wa.set("SOLAR",document.getElementById("solar"));Wa.set("MINER",document.getElementById("miner"));Wa.set("BATTERY",document.getElementById("battery"));
Wa.set("RTG",document.getElementById("rtg"));Wa.set("TELEDEPOT",document.getElementById("teledepot"));Wa.set("ROBOSHOP",document.getElementById("shop"));Wa.set("GENERATOR",document.getElementById("generator"));
function Xa(a){var b=a.o;c.beginPath();var d=b.x+60*Sa[0].x,h=b.y+24*Sa[0].y;c.moveTo(d,h);for(var e=1;e<Sa.length;e++)d=b.x+60*Sa[e].x,h=b.y+24*Sa[e].y,c.lineTo(d,h);c.closePath();c.fill();c.stroke();if(a.isVisible&&"NONE"!=a.i.type){d=Va.get(a.i.type);c.lineWidth=3;c.fillStyle=Oa(d);c.strokeStyle=Oa(Qa(d,.4));a=a.i.lines;c.beginPath();c.moveTo(a[0].x+b.x,a[0].y+b.y);for(d=1;d<a.length;d++)c.lineTo(a[d].x+b.x,a[d].y+b.y);c.closePath();c.fill();c.stroke()}}
function Ya(){var a=.71*q,b=r,d=f.find(function(e){return e.f}),h=f.filter(function(e){return 11>=Math.abs(e.x-d.x)}).sort(function(e,p){return e.height-p.height}).sort(function(e,p){return e.y-p.y}).sort(function(e,p){return e.isVisible-p.isVisible});h.forEach(function(e){e.o.x=90*e.x+t/2-90*d.x;e.o.y=41.569219381653056*e.y+a+(0!=e.x%2?20.784609690826528:0);if(e.isVisible){e.o.y-=e.height;var p=new Na(Math.max(0,e.H.r*(1-e.C/10)),Math.min(255,e.H.U*(1+e.C/10)),Math.max(0,e.H.S*(1-e.C/10)),255);c.strokeStyle=
0==e.C?Oa(Qa(p,.2)):Oa(Qa(p,1.5));c.fillStyle=Oa(p);v.includes(e)&&(w?c.strokeStyle="#FFFF00":x&&(c.strokeStyle="#FF0000"),v.indexOf(e)==y&&(c.strokeStyle="#00FF00"));c.lineWidth=3;Xa(e);p=Wa.get(e.a.type);void 0!=p?c.drawImage(p,Math.trunc(e.o.x-p.width/2),Math.trunc(e.o.y-.6*p.height)):null}else c.strokeStyle="#000000",c.fillStyle="#AAAAAA",c.lineWidth=3,Xa(e),c.fillStyle="#000000",c.font="24px Arial",c.textAlign="center",c.textBaseline="middle",z("404",e.o.x,e.o.y)});h=h.find(function(e){return e.f}).o;
Za?c.drawImage(n,h.x-Math.trunc(n.width*m/2)+Math.trunc(b.x),Math.trunc(h.y-n.height*m/2-10)+Math.trunc(b.y),Math.trunc(n.width*m),Math.trunc(n.height*m)):c.drawImage(n,h.x-Math.trunc(n.width*m/2)+Math.trunc(b.x),Math.trunc(h.y-n.height*m/2-10+4*Math.sin(Math.PI/180*A*180))+Math.trunc(b.y),Math.trunc(n.width*m),Math.trunc(n.height*m))}
function $a(){var a=f.filter(function(b){return"RADAR"==b.a.type});console.log(a.length);f.forEach(function(b){a.some(function(d){return Math.abs(d.x-b.x)<=ab})?b.isVisible=!0:b.isVisible=!1})}
function bb(){var a=.05*t,b=.07*q;c.save();c.translate(a,b);c.strokeStyle="#A2A2A2";c.beginPath();c.moveTo(0,-25);c.lineTo(-25,25);c.lineTo(25,25);c.closePath();c.stroke();c.fillStyle="#FF0000";c.beginPath();c.arc(0,-25,12.5,0,2*Math.PI);c.fill();c.fillStyle="#FFF500";c.beginPath();c.arc(-25,25,12.5,0,2*Math.PI);c.fill();c.fillStyle="#0045FF";c.beginPath();c.arc(25,25,12.5,0,2*Math.PI);c.fill();c.restore()}
function cb(a,b,d,h){var e=.25*d;c.save();c.translate(a,b);c.fillStyle=Oa(new Na(255-255*h,255*h,0,255));c.fillRect(0,-d*h,e,d*h);c.strokeStyle="#FFFFFF";c.beginPath();c.moveTo(0,-d);c.lineTo(e,-d);c.lineTo(e,0);c.lineTo(0,0);c.closePath();c.stroke();c.restore()}
function db(a,b){B=0;moving=!0;var d=f.find(function(e){return e.f}),h=f.find(function(e){return e.x==d.x+a&&e.y==d.y+b});null!=h&&(h.isVisible?Math.abs(h.height-d.height)<=5*eb?(d.f=!1,h.f=!0,r={x:d.o.x-h.o.x,y:d.o.y-h.o.y},C([D,.1,440,,,.07,,,,,50,.07])):g.push({text:"Incline too steep",time:0}):g.push({text:"Cannot enter unfound tile",time:0}))}function fb(a){"NONE"!=a.i.type&&(1==a.i.value?a.i={type:"NONE",value:0}:(--a.i.value,a.i.lines=mb(a.i.value,a.i.type)))}
function nb(a,b){a.a.type=b.type;var d=a.a;switch(b.type){case "RADAR":$a();break;case "CONSTRUCTOR":d.b=0;d.m=20;d.T=!1;d.K=0;d.N=!1;break;case "MINER":d.u=0;d.O=a.i.type;d.W=50;d.b=0;d.m=10;d.X=!1;d.M=0;break;case "BATTERY":d.b=0;d.m=20;d.L=0;d.P=!1;break;case "GENERATOR":d.I=0,d.Z=25,d.J=0,d.V=!1}--b.value;C([D,,191,,,.07,1,1.09,-5.4,,,,,.4,-.4,.3,,.7])}
function ob(){var a=v[y];switch(a.a.type){case "RADAR":var b=f.find(function(d){return d.f});1<=f.filter(function(d){return Math.abs(d.x-b.x)<=ab}).filter(function(d){return"RADAR"==d.a.type&&d!=a}).length?(pb(a.a.type),a.a={type:"NONE"},$a(),C([D,,400,,,.07,1,1.09,-5.4,,,,,.4,-.4,.3,,.7])):g.push({text:"No other radar in range",time:0});break;case "CONSTRUCTOR":1==a.a.N&&pb(a.a.D.product);pb(a.a.type);a.a={type:"NONE"};C([D,,400,,,.07,1,1.09,-5.4,,,,,.4,-.4,.3,,.7]);break;case "GENERATOR":qb("CARBON",
a.a.I);pb(a.a.type);a.a={type:"NONE"};C([D,,400,,,.07,1,1.09,-5.4,,,,,.4,-.4,.3,,.7]);break;default:pb(a.a.type),a.a={type:"NONE"},C([D,,400,,,.07,1,1.09,-5.4,,,,,.4,-.4,.3,,.7])}}function qb(a,b){var d=Math.min(rb,b),h=E.find(function(e){return e.type==a});null!=h?(h.value+d>rb&&(d=rb-h.value),h.value+=d):E.push({type:a,value:d});return d}function pb(a){var b=F.find(function(d){return d.type==a});null!=b?b.value+=1:F.push({type:a,value:1})}
function Pa(a){a=Math.trunc(a).toString(16);return 1==a.length?"0"+a:a}
function sb(){var a=55+25*E.length+.05*q,b=[];b.unshift({x:0,y:.29*q});b.unshift({x:.09*t,y:.29*q});b.unshift({x:.1*t,y:q*(.29-.02)});b.unshift({x:.1*t,y:0});b.unshift({x:0,y:0});b.unshift({x:0,y:.48*q});b.unshift({x:.09*t,y:.48*q});b.unshift({x:.1*t,y:q*(.48-.02)});b.unshift({x:.1*t,y:.29*q});b.unshift({x:0,y:.29*q});b.unshift({x:0,y:0});b.unshift({x:.39*t,y:0});b.unshift({x:.42*t,y:.04*q});b.unshift({x:.58*t,y:.04*q});b.unshift({x:.61*t,y:0});b.unshift({x:.83*t,y:0});b.unshift({x:.83*t,y:a-.02*
q});b.unshift({x:.85*t,y:a});b.unshift({x:t,y:a});b.unshift({x:t,y:0});b.unshift({x:0,y:0});return b}
function tb(a,b,d){var h=1-d;c.beginPath();c.moveTo(t*(d+.04),q*a);c.lineTo(t*(h-.04),q*a);c.lineTo(t*h,q*(a+.04));c.lineTo(t*h,q*(a+b-.04));c.lineTo(t*(h-.04),q*(a+b));c.lineTo(t*(d+.04),q*(a+b));c.lineTo(t*d,q*(a+b-.04));c.lineTo(t*d,q*(a+.04));c.closePath();c.fill();c.stroke();a+=.02;b-=.04;c.beginPath();c.moveTo(t*(d+.02+.04),q*a);c.lineTo(t*(h-.02-.04),q*a);c.lineTo(t*(h-.02),q*(a+.04));c.lineTo(t*(h-.02),q*(a+b-.04));c.lineTo(t*(h-.02-.04),q*(a+b));c.lineTo(t*(d+.02+.04),q*(a+b));c.lineTo(t*
(d+.02),q*(a+b-.04));c.lineTo(t*(d+.02),q*(a+.04));c.closePath();c.fill();c.stroke()}function ub(a){return f.filter(function(b){var d=b.y-a.y;b=b.x-a.x;if(1==Math.abs(d)&&0==b||0==d&&1==Math.abs(b))return!0;if(0==a.x%2){if(-1==d&&1==Math.abs(b))return!0}else if(1==d&&1==Math.abs(b))return!0;return!1})}
function mb(a,b){switch(b){case "ROCK":var d=12;break;case "SILICON":d=5;break;case "LITHIUM":d=9;break;case "CARBON":d=15;break;default:d=7}for(var h=a/20,e=12*(Math.random()-.5)*h,p=12*(Math.random()-.5)*h,u=[],l=0;l<d;l++){var k=2*Math.PI/d*l;u.unshift({x:Math.max(-31,Math.min(31,e+(Math.cos(k)*h*60+15*Math.random()*h))),y:Math.max(-19,Math.min(19,p+(Math.sin(k)*h*24+15*Math.random()*h*.4)))})}return u}
function wb(a){var b=xb;f=[];for(var d=0;5>d;d++)for(var h=0;500>h;h++)f.push(new Ma(h,d,a[h]));f.forEach(function(e){var p=Math.trunc(Math.abs((Ka(e.x/10,e.y/10)+1)/2*(3+2*e.$)));e.height=5*p;e.H=b.find(function(u){return u.R.includes(p)}).H;2.5<Math.abs(240-e.x)&&.85<Math.random()?yb(e,"IRON",.6):25<Math.abs(240-e.x)&&.9<Math.random()?yb(e,"COPPER",.5):40<Math.abs(240-e.x)&&.92<Math.random()?yb(e,"CARBON",.6):60<Math.abs(240-e.x)&&.96<Math.random()?yb(e,"LITHIUM",.6):70<Math.abs(240-e.x)&&.85<Math.random()?
yb(e,"SILICON",.5):120<Math.abs(240-e.x)&&.85<Math.random()?(yb(e,"PLUTONIUM",.7),zb(e,4)):.88<Math.random()&&yb(e,"ROCK",.9);80<Math.abs(240-e.x)&&.95<Math.random()&&zb(e,5*Math.random())});f.find(function(e){return 240==e.x}).f=!0;f.filter(function(e){return"NONE"!=e.i.type}).forEach(function(e){return e.i.lines=mb(e.i.value,e.i.type)})}
function yb(a,b,d){var h=Math.max(10,Math.trunc(15*Math.random()));a.i={type:b,value:h};ub(a).filter(function(){return Math.random()>d}).forEach(function(e){return e.i={type:b,value:Math.max(5,Math.trunc(h*Math.random()))}})}function zb(a,b){a.C=b;ub(a).forEach(function(d){return d.C=.8*b})}var Ab="Resume;Main Menu;Save Game;Load Game;Mute Music;Mute Sound FX".split(";"),G=0,Bb=["New Game","Load Game","Mute Music","Mute Sound FX"],Cb=!0,D=0;
function Db(){zzfx.apply(null,[D,.01,593,,.03,0,1,2.04,.1,.1,50,.01,,-.1,,,.06,.96,.08]).start()}function Eb(){zzfx.apply(null,[D,0,604,,,.13,4,2.01,-.1,.2,50,,.01,,,.4,.05,.68,.05]).start()}
var Fb=[{product:"EXIT",items:[],b:0},{product:"RADAR",items:[{type:"IRON",value:18}],b:8}],Gb=[{type:"ROCK",A:1},{type:"IRON",A:5},{type:"COPPER",A:25},{type:"CARBON",A:50},{type:"LITHIUM",A:75},{type:"SILICON",A:100},{type:"PLUTONIUM",A:200}],Hb=Array.from(Array(21).keys()).map(function(a){var b=Math.trunc(a/3),d=Gb[b];return{type:d.type,A:d.A,s:[1,10,50][a-3*b]}});Hb.unshift({type:"EXIT",A:0,s:0});
var Ib=[{type:"EXIT",item:"EXIT",j:0,B:0,l:[]},{type:"CRAFT UPGRADES",item:"RESOURCE STORAGE",j:350,B:2,l:["Increases JMC\u2122 Craft resource","capacity by 20%"]},{type:"CRAFT UPGRADES",item:"BATTERY EFFICENCY",j:200,B:1.6,l:["Increases JMC\u2122 Craft battery capacity","by 25%"]},{type:"CRAFT UPGRADES",item:"CRAFT HEIGHT TOLERANCE",j:350,B:1.5,l:["Allows JMC\u2122 Craft to","move between tiles","with a larger height","difference."]},{type:"RECIPES",item:"CONSTRUCTOR",j:500,l:["Adds JMC\u2122 Constructor to",
"Constructor Database.","Constructors manufacture other","JMC\u2122 Buildings."]},{type:"RECIPES",item:"MINER",j:750,l:"Adds JMC\u2122 Miner to Constructor;Database.;JMC\u2122 Miners use energy to;gather resources 5 times;more efficent than;the JMC\u2122 Craft".split(";")},{type:"RECIPES",item:"GENERATOR",j:1025,l:["Adds JMC\u2122 Generator to Constructor","Database.","JMC\u2122 Generators create energy from","carbon."]},{type:"RECIPES",item:"SOLAR",j:1250,l:["Adds JMC\u2122 Solar Panel to","Constructor Database.",
"JMC\u2122 Solar Panels generate","fluctuating energy."]},{type:"RECIPES",item:"BATTERY",j:1650,l:["Adds JMC\u2122 Battery to","Constructor Database.","JMC\u2122 Batteries store","energy and release it","periodically."]},{type:"RECIPES",item:"RTG",j:2500,l:["Adds JMC\u2122 RTG to","Constructor Database.","JMC\u2122 RTGs generate","constant energy."]},{type:"BUILDING UPGRADES",item:"RADAR RADIUS",j:1E3,B:1.5,l:["Increases JMC\u2122 Radar uncover","distance by 3 tiles."]},{type:"BUILDING UPGRADES",
item:"CONSTRUCTOR SPEED",j:200,B:1.8,l:["Increases JMC\u2122 Constructor speed","by 30%"]},{type:"BUILDING UPGRADES",item:"CONSTRUCTOR TRANSMITTER",j:1850,l:["JMC\u2122 Constructor transmits","finished constructions to","JMC\u2122 Craft."]},{type:"BUILDING UPGRADES",item:"MINER SPEED",j:750,l:["Increases JMC\u2122 Miner speed","by 50%"]},{type:"BUILDING UPGRADES",item:"MINER TRANSMITTER",j:1985,l:["JMC\u2122 Miner transmits","mined resources to","JMC\u2122 Craft."]},{type:"BUILDING UPGRADES",item:"RTG OUTPUT",
j:250,B:1.8,l:["Increases JMC\u2122 RTG output","by 1."]},{type:"BUILDING UPGRADES",item:"SOLAR OUTPUT",j:750,B:1.4,l:["Increases JMC\u2122 Solar Panel output","by 1."]},{type:"BUILDING UPGRADES",item:"GENERATOR OUTPUT",j:500,B:2,l:["Increases JMC\u2122 Generator output","by 1."]}],H=Ib.slice(),Jb=Fb.slice(),Kb=1,I=50,Lb=50,Za=!1,Mb,Nb=0,Ob=[800,1500,2500,5E3,1E4,2E4,5E4],Pb=!1,Qb=!1,t=1280,q=720;Ra.width=t;Ra.height=q;Ra.style.width=Ra.width+"px";Ra.style.height=Ra.height+"px";
var J={h:!1,g:!1,left:!1,right:!1,c:!1,F:!1,remove:!1,v:!1,G:!1},K={h:!1,g:!1,left:!1,right:!1,c:!1,F:!1,remove:!1,v:!1,G:!1},r={x:0,y:0};f=[];g=[];var v=[],y=0,L=0,Rb=0,M=0,E,F,N=0,w=!1,x=!1,O=!1,Q=!1,S=!1,W=!1,Sb=!1,X,eb,rb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ab,A,ac,bc=0,dc=!1,ec=!1,B=0,fc=1,gc="Nominal",hc=zzfxM.apply(null,ba(za)),ic=zzfxP.apply(null,ba(hc));ic.loop=!0;ic.start();var jc=Array.from(Array(500).keys()).map(function(){return{x:2*Math.random()*t-t,y:2*Math.random()*q-q,r:3*Math.random()}});Ia(Math.random());
var xb=[{R:[0,1,2],H:new Na(62,47,91,255)},{R:[3,4],H:new Na(190,184,235,255)},{R:[5,6,7],H:new Na(64,121,140,255)},{R:[8,9],H:new Na(115,251,211,255)}],kc=!1,lc=!1;function z(a,b,d){return c.fillText(a,b,d)}var mc=(new Date).getTime(),Z=0;
function nc(){c.fillStyle="#FFFFF0";c.save();c.translate(t/2,q/2);jc.forEach(function(a){c.beginPath();c.arc(a.x,a.y,a.r,0,2*Math.PI);c.fill()});c.restore();c.fillStyle="#FFFFFF";c.textAlign="center";c.textBaseline="middle";c.font="65px Tahoma";z("Planet 404",t/2,.1*q);1==K.h&&0==J.h&&(G=Math.max(0,G-1),C([]));1==K.g&&0==J.g&&(G=Math.min(Bb.length-1,G+1),C([]));if(1==K.c&&0==J.c){switch(Bb[G]){case "New Game":oc();D=.5;Cb=!1;G=0;lc=!0;break;case "Load Game":pc();D=.5;kc=!0;Cb=!1;G=0;break;case "Mute Music":ic.disconnect();
Bb[G]="Unmute Music";break;case "Mute Sound FX":D=0;Bb[G]="Unmute Sound FX";break;case "Unmute Music":ic.connect(zzfxX.destination);Bb[G]="Mute Music";break;case "Unmute Sound FX":D=1,Bb[G]="Mute Sound FX"}Db()}c.font="40px Tahoma";Bb.forEach(function(a){var b=Bb.indexOf(a);if(G==b){var d=c.measureText(a).width;c.drawImage(n,Math.trunc(.45*t-.5*d-.5*n.width),Math.trunc(.3*q+80*b-.5*n.height));c.drawImage(n,Math.trunc(.55*t+.5*d-.5*n.width),Math.trunc(.3*q+80*b-.5*n.height));c.fillStyle="#FFFFFF"}else c.fillStyle=
"#AAAAAA";z(a,.5*t,.3*q+80*b)})}
function oc(){var a=Array.from(Array(500).keys()).map(function(b){return Math.min(4,Math.abs(Math.trunc(5*Math.cos(Math.abs(240-b)/250*Math.PI*2))))});wb(a);db(0,0);F=[{type:"RADAR",value:1}];E=[];Mb=0;Jb=Fb.slice();H=Ib.slice();Sb=!1;I=X=50;eb=1;rb=50;Ub=Tb=1;Vb=3;Xb=Wb=!1;Yb=2.5;Zb=5;ab=6;ac=A=0;Pb=!1;J={h:!1,g:!1,left:!1,right:!1,c:!1,F:!1,remove:!1,info:!1,v:!1,G:!1};K={h:!1,g:!1,left:!1,right:!1,c:!1,F:!1,remove:!1,info:!1,v:!1,G:!1};nb(f.find(function(b){return 240==b.x&&2==b.y}),{type:"RADAR",
value:1});nb(f.find(function(b){return 240==b.x&&0==b.y}),{type:"RTG",value:1});nb(f.find(function(b){return 239==b.x&&0==b.y}),{type:"CONSTRUCTOR",value:1});nb(f.find(function(b){return 243==b.x&&2==b.y}),{type:"TELEDEPOT",value:1});nb(f.find(function(b){return 237==b.x&&1==b.y}),{type:"ROBOSHOP",value:1})}
function qc(){c.fillStyle="#FFFFF0";c.save();c.translate(t/2,q/2);c.rotate(Math.PI/180*(360*ac+A));jc.forEach(function(d){c.beginPath();c.arc(d.x,d.y,d.r,0,2*Math.PI);c.fill()});c.restore();Ya();c.fillStyle="#FFFFFF";c.textAlign="center";if(!Q||Za||Pb)if(Za||Pb||Qb)if(Za){r.y=Ja(r.y,10,Z/1500);m=Ja(m,0,Z/1500);var b=Math.trunc(50-50*m);c.font=b+"px Arial";c.fillStyle="#FFFFFF";c.strokeStyle="#000000";c.textAlign="center";c.textBaseline="middle";z("You Died",t/2,.2*q);.4>m&&(z("Press E/Space to respawn",
t/2,.3*q),1==K.c&&0==J.c&&(I=X,E=[],F=[],f.find(function(d){return d.f}).f=!1,f.find(function(d){return 240==d.x}).f=!0,db(0,0),Za=!1,m=1,r={x:0,y:0}))}else Pb?(r.y=Ja(r.y,10,Z/1500),m=Ja(m,0,Z/1500),b=Math.trunc(50-50*m),c.font=b+"px Arial",c.fillStyle="#FFFFFF",c.strokeStyle="#000000",c.textAlign="center",c.textBaseline="middle",z("Quota Failed",t/2,.2*q),f.forEach(function(d){return d.C=Math.min(6,d.C+Z/800)}),.4>m&&(z("Press E to return to main menu",t/2,.3*q),1==K.c&&0==J.c&&(Cb=!0,Pb=kc=Q=!1,
G=0,m=1)),.8<m?(c.fillStyle="#FFFFFF"+Pa(255-(1-m)/.2*255),c.beginPath(),c.arc(t/2,q/2,(1-m)/.2*t,0,2*Math.PI),c.fill()):(c.fillStyle="#FFFFFF"+Pa(m/.8*255),c.fillRect(0,0,t,q))):Qb&&(c.strokeStyle="#FFFFFF",c.fillStyle="#000000A",tb(.05,.5,.2),b=t/2*.45,c.font="20px Arial",c.fillStyle="#FFFFFF",c.strokeStyle="#000000",c.textAlign="start",c.textBaseline="alphabetic",z("Congratulations, you have completed all JMC\u2122 Mining Initative quotas.",b,.2*q),z("Due to the costs of JMC\u2122 Craft recovery, you have been offered an",
b,25+.2*q),z("involutary position as cheif of planetary excavations and are forbidden",b,50+.2*q),z("from leaving this planet.",b,75+.2*q),c.textAlign="center",z("Thanks for playing!",t/2,.45*q),1.5<=A&&(z("Press E to enter endless mode",t/2,25+.45*q),1==K.c&&0==J.c&&(Sb=!0,Qb=!1)));else{f.filter(function(d){return d.isVisible&&"NONE"!=d.a.type}).forEach(function(d){return rc(d)});r.x=Ja(r.x,0,Z/150*Kb);r.y=Ja(r.y,0,Z/150*Kb);1==K.G&&0==J.G?Kb=1.8:0==K.G&&1==J.G&&(Kb=1);E=E.filter(function(d){return 0<
d.value});L=Math.min(Hb.filter(function(d){return E.some(function(h){return d.type==h.type&&h.value>=d.s})||"EXIT"==d.type}).length-1,L);F=F.filter(function(d){return 0<d.value});M=Math.min(H.length-1,M);!w||0!=F.length&&v.some(function(d){return"NONE"==d.a.type})||(y=0,w=!1,v=[]);x&&!v.some(function(d){return"NONE"!=d.a.type})&&(y=0,x=!1,v=[]);S&&0==Hb.filter(function(d){return E.some(function(h){return d.type==h.type&&h.value>=d.s})}).length&&(L=0,S=!1);var a=f.find(function(d){return d.f});Lb<
I?(dc=!1,gc="Charging"):S||W||["SOLAR","RTG","GENERATOR"].some(function(d){return d==a.a.type})?(dc=!1,gc="Paused"):I-=Z/1E3*(1+a.C);sc();tc()}else if(c.textBaseline="middle",c.font="45px Tahoma",z("Paused",t/2,30),c.font="35px Tahoma",Ab.forEach(function(d){var h=Ab.indexOf(d);if(G==h){var e=c.measureText(d).width;c.drawImage(n,Math.trunc(.45*t-.5*e-.5*n.width),Math.trunc(.15*q+50*h-.5*n.height));c.drawImage(n,Math.trunc(.55*t+.5*e-.5*n.width),Math.trunc(.15*q+50*h-.5*n.height));c.fillStyle="#FFFFFF"}else c.fillStyle=
"#AAAAAA";z(d,.5*t,.15*q+50*h)}),0==K.h&&1==J.h&&(G=Math.max(0,G-1),C([])),0==K.g&&1==J.g&&(G=Math.min(Ab.length-1,G+1),C([])),1==K.v&&0==J.v&&(Q=!1),0==K.c&&1==J.c){switch(Ab[G]){case "Resume":Q=!1;break;case "Main Menu":Cb=!0;kc=Q=!1;G=0;break;case "Save Game":window.localStorage.setItem("Planet404_6473_DATA",JSON.stringify([f,A,ac,E,F,Mb,I,Jb,H,X,eb,rb,ab,Tb,Ub,Vb,Wb,Xb,Yb,Zb,Sb]));g.push({text:"Game Saved",time:0});Q=!1;break;case "Load Game":pc();Q=!1;break;case "Mute Music":ic.disconnect();
Ab[G]="Unmute Music";break;case "Mute Sound FX":D=0;Ab[G]="Unmute Sound FX";break;case "Unmute Music":ic.connect(zzfxX.destination);Ab[G]="Mute Music";break;case "Unmute Sound FX":D=1,Ab[G]="Mute Sound FX"}Db()}0>=I&&!Za&&(Za=!0,C([D,,160,.01,.2,.04,2,,-.1,.1,-100,.1]));Lb=I;Za||(A+=Z/800);359<=A&&(Mb>=Ob[ac]&&!Qb&&!Sb?(Mb-=Ob[ac],ac==Ob.length-1?(Qb=!0,C([D,0,220,,2,.08,1.5,,,,50,.07,.1,,,,.01])):C([D,0,160,,1,.04,2,,,,25,.07,.03,,,,.01])):Qb||Sb||Pb||(Pb=!0,C([D,,299,.01,.03,1.95,3,.1,.9,.6,,,,
.5,.9,.6,,.52,.06]),C([D,0,160,,1.25,.04,2,,,,-25,.25,.01,,,,.01])),ac+=1);A=359<=A?0:A}
function tc(){!(1!=K.h||0!=J.h||w||x||O||Q||S||W)&&10>Math.abs(r.y)&&db(0,-1);!(1!=K.g||0!=J.g||w||x||O||Q||S||W)&&10>Math.abs(r.y)&&db(0,1);!(1!=K.h||1!=J.h||w||x||O||Q||S||W)&&10>Math.abs(r.y)&&db(0,-1);!(1!=K.g||1!=J.g||w||x||O||Q||S||W)&&10>Math.abs(r.y)&&db(0,1);1==K.h&&0==J.h&&w&&(N=Math.max(0,N-1),C([]));1==K.g&&0==J.g&&w&&(N=Math.max(0,Math.min(F.length-1,N+1)),C([]));1==K.h&&0==J.h&&O&&(N=Math.max(0,N-1),C([]));1==K.g&&0==J.g&&O&&(N=Math.max(0,Math.min(Jb.length-1,N+1)),C([]));1==K.h&&0==
J.h&&S&&(B=0,L=Math.max(0,L-1),C([]));1==K.g&&0==J.g&&S&&(B=0,L=Math.min(Hb.filter(function(b){return E.some(function(d){return b.type==d.type&&d.value>=b.s})||"EXIT"==b.type}).length-1,L+1),C([]));1==K.h&&0==J.h&&W&&(B=0,M=Math.max(0,M-1),C([]));1==K.g&&0==J.g&&W&&(B=0,M=Math.min(H.length-1,M+1),C([]));1==K.h&&1==J.h&&S&&(1<=B?(L=Math.max(0,L-1),B=0,C([])):B+=Z/100);1==K.g&&1==J.g&&S&&(1<=B?(L=Math.min(Hb.filter(function(b){return E.some(function(d){return b.type==d.type&&d.value>=b.s})||"EXIT"==
b.type}).length-1,L+1),B=0,C([])):B+=Z/100);1==K.h&&1==J.h&&W&&(1<=B?(M=Math.max(0,M-1),B=0,C([])):B+=Z/100);1==K.g&&1==J.g&&W&&(1<=B?(M=Math.min(H.length-1,M+1),B=0,C([])):B+=Z/100);!(1!=K.right||0!=J.right||w||x||Q||S||W)&&10>Math.abs(r.x)&&db(1,0);!(1!=K.left||0!=J.left||w||x||Q||S||W)&&10>Math.abs(r.x)&&db(-1,0);!(1!=K.right||1!=J.right||w||x||Q||S||W)&&10>Math.abs(r.x)&&db(1,0);!(1!=K.left||1!=J.left||w||x||Q||S||W)&&10>Math.abs(r.x)&&db(-1,0);1==K.right&&0==J.right&&(w||x)&&(y=y==v.length-1?
0:y+1);1==K.left&&0==J.left&&(w||x)&&(y=0==y?v.length-1:y-1);if(1==K.c&&0==J.c&&!w&&!x&&!Q){fc=1;B=0;var a=f.find(function(b){return b.f});"NONE"!=a.a.type?uc(a):"NONE"!=a.i.type&&(0<qb(a.i.type,1)?(fb(a),C([D,0,320,.02-a.i.value/1E3,,0,4,.1,,,,,,,,.2,.01,0,.01])):g.push({text:"Resource full",time:0}))}a=f.find(function(b){return b.f});1==K.c&&1==J.c&&!w&&!x&&!Q&&1<=B?(B=0,a=f.find(function(b){return b.f}),"NONE"!=a.a.type?uc(a):"NONE"!=a.i.type&&(0<qb(a.i.type,1)?(fb(a),C([D,0,320,.02-a.i.value/
1E3,,0,4,.1,,,,,,,,.2,.01,0,.01])):g.push({text:"Resource full",time:0}))):1!=K.c||1!=J.c||w||x||Q||(B+=Z/100*fc);1!=K.F||0!=J.F||w||x||O||Q||S||W?1==K.F&&0==J.F&&w&&(y=0,w=!1,v=[]):0<F.length?(N=0,w=!0,v=ub(f.find(function(b){return b.f})).filter(function(b){return b.isVisible&&"NONE"==b.a.type}).sort(function(b,d){return b.y-d.y}).sort(function(b,d){return b.x-d.x}),v.forEach(function(b){return b.highlighted=!0})):g.push({text:"No Buildings",time:0});1!=K.remove||0!=J.remove||w||x||O||S||W||Q?1==
K.remove&&0==J.remove&&x&&(y=0,x=!1,v=[]):(x=!0,v=ub(f.find(function(b){return b.f})).filter(function(b){return b.isVisible&&"NONE"!=b.a.type}).sort(function(b,d){return b.y-d.y}).sort(function(b,d){return b.x-d.x}),v.forEach(function(b){return b.highlighted=!0}));w&&1==K.c&&0==J.c&&v.some(function(b){return"NONE"==b.a.type})&&(nb(v[y],F[N]),F=F.filter(function(b){return 0<b.value}),v[y].highlighted=!1,v=v.filter(function(b){return b!=v[y]}),y=Math.min(v.length-1,y),N=Math.min(F.length-1,N));x&&1==
K.c&&0==J.c&&v.some(function(b){return"NONE"!=b.a.type})&&(ob(),v[y].highlighted=!1,v=v.filter(function(b){return b!=v[y]}),y=Math.min(v.length-1,y));1==K.v&&0==J.v&&(w||x||S||W||O)?(O=W=S=x=w=!1,v=[],S=N=y=0):1==K.v&&0==J.v&&(Q=!0)}
function pc(){O=W=S=x=w=!1;v=[];S=N=y=0;var a=JSON.parse(window.localStorage.getItem("Planet404_6473_DATA"));f=a[0];A=a[1];ac=a[2];E=a[3];F=a[4];Mb=a[5];I=a[6];Jb=a[7];H=a[8];X=a[9];eb=a[10];rb=a[11];ab=a[12];Tb=a[13];Ub=a[14];Vb=a[15];Wb=a[16];Xb=a[17];Yb=a[18];Zb=a[19];Sb=a[20];db(0,0)}
function uc(a){switch(a.a.type){case "CONSTRUCTOR":if(O){var b=Object.assign({},Jb[N]);if("EXIT"!=b.product)if(a.a.b>=b.b){var d=b.items;d.filter(function(e){return E.some(function(p){return p.type==e.type&&p.value>=e.value})}).length==d.length?(a.a.D=b,E.forEach(function(e){var p=d.find(function(u){return u.type==e.type});null!=p&&(e.value-=p.value,g.push({text:"Used "+p.value+" units of "+e.type,time:0}))}),a.a.T=!0,a.a.b-=b.b,Db()):(d.forEach(function(e){var p=E.find(function(u){return u.type==
e.type&&u.value<e.value});null!=p?g.push({text:e.value-p.value+" more "+e.type+" needed",time:0}):E.some(function(u){return u.type==e.type})||g.push({text:e.value+" more "+e.type+" needed",time:0})}),Eb())}else g.push({text:"Not enough energy",time:0});O=!1}else a.a.N?(pb(a.a.D.product),g.push({text:"Gained "+a.a.D.product,time:0}),a.a.N=!1,a.a.D=null,a.a.K=0,Db()):null==a.a.D&&(O=!0,N=0);break;case "MINER":Wb||(0==a.a.u?g.push({text:"Resource full",time:0}):(b=qb(a.a.O,a.a.u),0==b?(Eb(),g.push({text:"Resource full"+
b+a.a.O,time:0})):(a.a.u-=qb(a.a.O,a.a.u),g.push({text:"Gained "+b+a.a.O,time:0}),Db())));break;case "TELEDEPOT":if(S){var h=Hb.filter(function(e){return E.some(function(p){return e.type==p.type&&p.value>=e.s})||"EXIT"==e.type})[L];"EXIT"!=h.type?(a=E.find(function(e){return e.type==h.type}),a.value>=h.s?(a.value-=h.s,Mb+=h.s*h.A,C([D,.01,287,.11,,0,3,.01,,,198,.09,,,,,.06,.5])):g.push({text:"Cannot sell "+h.s+" of "+h.type,time:0})):(L=0,S=!1)}else L=0,S=!0;break;case "ROBOSHOP":if(W)if("EXIT"!=
H[M].type)if(Mb>=H[M].j){Mb-=H[M].j;switch(H[M].item){case "RESOURCE STORAGE":rb=Math.round(1.2*rb);break;case "BATTERY EFFICENCY":X=Math.round(1.25*X);break;case "CRAFT HEIGHT TOLERANCE":eb+=1;break;case "CONSTRUCTOR SPEED":Ub*=1.3;break;case "CONSTRUCTOR TRANSMITTER":Xb=!0;H=H.filter(function(e){return"CONSTRUCTOR TRANSMITTER"!=e.item});break;case "MINER SPEED":Vb*=1.5;break;case "MINER TRANSMITTER":Wb=!0;H=H.filter(function(e){return"MINER TRANSMITTER"!=e.item});break;case "RTG OUTPUT":Zb+=1;break;
case "SOALR OUTPUT":Tb+=1;break;case "GENERATOR OUTPUT":$b+=1;break;case "RADAR RADIUS":ab+=3;$a();break;case "CONSTRUCTOR":Jb.push({product:"CONSTRUCTOR",items:[{type:"IRON",value:10},{type:"COPPER",value:15}],b:4});H=H.filter(function(e){return"CONSTRUCTOR"!=e.item});break;case "MINER":Jb.push({product:"MINER",items:[{type:"IRON",value:10},{type:"COPPER",value:15},{type:"CARBON",value:8}],b:4});H=H.filter(function(e){return"MINER"!=e.item});break;case "GENERATOR":Jb.push({product:"GENERATOR",items:[{type:"IRON",
value:20},{type:"COPPER",value:25},{type:"ROCK",value:15}],b:5});H=H.filter(function(e){return"GENERATOR"!=e.item});break;case "BATTERY":Jb.push({product:"BATTERY",items:[{type:"IRON",value:10},{type:"COPPER",value:10},{type:"LITHIUM",value:5}],b:8});H=H.filter(function(e){return"BATTERY"!=e.item});break;case "SOLAR":Jb.push({product:"SOLAR",items:[{type:"COPPER",value:5},{type:"SILICON",value:10}],b:10});H=H.filter(function(e){return"SOLAR"!=e.item});break;case "RTG":Jb.push({product:"RTG",items:[{type:"IRON",
value:25},{type:"COPPER",value:25},{type:"PLUTONIUM",value:10}],b:10}),H=H.filter(function(e){return"RTG"!=e.item})}null!=H[M].B&&(H[M].j=Math.round(H[M].j*H[M].B));Db()}else g.push({text:"Cannot afford "+H[M].item,time:0}),Eb();else W=!1;else W=!0;break;case "GENERATOR":b=E.find(function(e){return"CARBON"==e.type}),null!=b?a.a.I<a.a.Z?(a.a.I+=1,--b.value,Db()):g.push({text:"Generator is full",time:0}):(g.push({text:"No available carbon",time:0}),Eb())}}
function sc(){var a=.12*q;dc?1<=bc&&(C([D,0,500,.2,,0,1,.5,,,50,.12,,,,,,,.01]),ec=!ec,bc=0):ec=!1;c.strokeStyle=ec?"#FF0000":"#FFFFFF";c.fillStyle="#000000AA";var b=sb();c.beginPath();for(var d=0;d<b.length;d++)0==d?c.moveTo(b[d].x,b[d].y):c.lineTo(b[d].x,b[d].y);c.closePath();c.fill();c.stroke();c.font="15px Arial";c.fillStyle="#FFFFFF";c.textAlign="start";g=g.slice(-3,5);g=g.filter(function(l){return 2E3>l.time});var h=25*g.length;g.forEach(function(l){z(l.text,.01*t,.42*q+150-h+25*g.indexOf(l));
l.time+=Z});c.textAlign="center";c.textBaseline="middle";c.font="25px Arial";z("Inventory",.92*t,30);c.font="15px Arial";E.forEach(function(l){z(l.value+"/"+rb+" units of "+l.type,.92*t,80+25*E.indexOf(l))});z("Sol: "+(ac+1)+" Planet Rotation: "+A.toFixed(0)+"\u00b0",t/2,15);w||x||O||S||W||!(8>=A||352<=A)||(c.fillStyle="#000000AA",3>A||357<=A?(c.strokeStyle="#FFFFFF",tb(.05,.14,.39),c.font="30px Tahoma",c.fillStyle="#FFFFFF",z("Sol "+(ac+1)+"/7",t/2,a)):8>=A?(b=Pa(255-(A-3)/5*255),c.strokeStyle="#FFFFFF"+
b,tb(.05,.14,.39),c.font="30px Tahoma",c.fillStyle="#FFFFFF"+b,z("Sol "+(ac+1)+"/7",t/2,a)):352<=A&&(b=Pa((A-352)/5*255),c.strokeStyle="#FFFFFF"+b,tb(.05,.14,.39),c.font="30px Tahoma",c.fillStyle="#FFFFFF"+b,z("Sol "+(ac+1)+"/7",t/2,a)));c.strokeStyle="#FFFFFF";if(w){c.fillStyle="#000000AA";tb(.05,.5,.4);c.font="30px Tahoma";c.fillStyle="#FFFFFF";z("Build Mode",t/2,a);c.font="20px Tahoma";var e=5,p=F.filter(function(l){return Math.abs(F.indexOf(l)-N)<e+Math.max(0,e-1-N)});p.forEach(function(l){var k=
F.indexOf(l);c.fillStyle="#AAAAAA";N==k&&(c.fillStyle="#FFFFFF");"EXIT"!=l.type?z(l.value+" "+l.type,t/2,a+40+25*p.indexOf(l)):z(l.type,t/2,a+40+25*p.indexOf(l))})}x&&(c.fillStyle="000000AA",tb(.05,.14,.39),c.fillStyle="#FFFFFF",c.font="30px Tahoma",z("Remove Mode",t/2,a));O&&(c.fillStyle="#000000AA",tb(.05,.5,.3),c.fillStyle="#FFFFFF",c.beginPath(),c.moveTo(.5*t,.07*q),c.lineTo(.5*t,.53*q),c.stroke(),c.font="30px Tahoma",z("Set Recipe:",.4*t,a+.01*t),c.font="20px Tahoma",e=5,p=Jb.filter(function(l){return Math.abs(Jb.indexOf(l)-
N)<e+Math.max(0,e-1-N)}),p.forEach(function(l){var k=Jb.indexOf(l);c.fillStyle="#AAAAAA";N==k&&(c.fillStyle="#FFFFFF");"EXIT"!=l.product&&(N==k&&(c.font="25px Tahoma",l.items.forEach(function(T){return z(T.value+" "+T.type,.59*t,a+.01*t+40+25*l.items.indexOf(T))}),z(l.b+" ENERGY",.59*t,a+.01*t+40+25*l.items.length)),c.font="20px Tahoma");z(l.product,.4*t,a+.01*t+40+25*p.indexOf(l))}));if(S){c.fillStyle="#000000AA";tb(.05,.5,.4);c.fillStyle="#FFFFFF";c.font="30px Tahoma";z("Sell Mode",t/2,a);c.font=
"20px Tahoma";e=5;var u=Hb.filter(function(l){return E.some(function(k){return l.type==k.type&&k.value>=l.s})||"EXIT"==l.type});p=u.filter(function(l){return Math.abs(u.indexOf(l)-L)<e+Math.max(0,e-1-L)});p.forEach(function(l){var k=u.indexOf(l);c.fillStyle="#AAAAAA";L==k&&(c.fillStyle="#FFFFFF");"EXIT"!=l.type?z(l.s+" "+l.type+" : \u20bf"+l.A*l.s,t/2,a+40+25*p.indexOf(l)):z(l.type,t/2,a+40+25*p.indexOf(l))})}W&&(c.fillStyle="#000000AA",tb(.05,.5,.2),c.fillStyle="#FFFFFF",c.beginPath(),c.moveTo(.5*
t,.07*q),c.lineTo(.5*t,.53*q),c.stroke(),"EXIT"!=H[M].type&&(c.beginPath(),c.moveTo(.5*t,.46*q),c.lineTo(.78*t,.46*q),c.stroke()),c.font="30px Tahoma",z("Buy Mode",.36*t,a),c.font="20px Tahoma",e=5,p=H.filter(function(l){return Math.abs(H.indexOf(l)-M)<e+Math.max(0,e-1-M)}),p.forEach(function(l){var k=H.indexOf(l);c.fillStyle="#AAAAAA";M==k&&(c.fillStyle="#FFFFFF");c.textAlign="center";c.textBaseline="middle";"EXIT"!=l.type?(z(l.item,.36*t,a+20+40+25*p.indexOf(l)),M==k&&(z(l.type,.65*t,a+20),z("\u20bf"+
Rb.toLocaleString("en-US",{maximumFractionDigits:0}),.64*t,.495*q),c.textAlign="start",l.l.forEach(function(T){return z(T,.51*t,a+20+40+25*l.l.indexOf(T))}))):z(l.type,.36*t,a+20+40+25*p.indexOf(l))}),Rb=Ja(H[M].j,Rb,Z/80));c.textAlign="center";c.textBaseline="middle";c.fillStyle="#FFFFFF";c.font="20px Tahoma";z("JMC",.05*t,.14*q);bb();Sb?(z("Endless",.05*t,.22*q),z("Mode",.05*t,25+.22*q)):z("Daily Quota:",.05*t,.22*q);c.font="25px Tahoma";z("\u20bf"+Nb.toLocaleString("en-US",{maximumFractionDigits:0}),
.05*t,.18*q);Nb=Ja(Mb,Nb,Z/100);Sb||(Mb>=Ob[ac]?c.fillStyle="#00FF00":300<A&&0==Math.trunc(A)%2&&(c.fillStyle="#FF0000"),z("\u20bf"+Ob[ac].toLocaleString("en-US",{maximumFractionDigits:0}),.05*t,.26*q));c.fillStyle="#FFFFFF";c.font="15px Tahoma";cb(.02*t,.45*q,100,I/X);ec&&(c.fillStyle="#FF0000");z("Battery",.07*t,.32*q);z("Status:",.07*t,.34*q);b=I/X;c.font="12px Tahoma";z(gc,.07*t,.36*q);c.fillStyle="#FFFFFF";0<f.find(function(l){return l.f}).C&&(c.font="50px Tahoma",z("\u2622",.07*t,q*(.45-.032)));
.6<b?(gc="Nominal",dc=!1):.4<b?(gc="Satisfactory",dc=!1):.3<b?(gc="Low",dc=!1,bc=0):15>=I&&10<I?(gc="Very Low",dc=!0,bc+=Z/400):10>=I&&5<I?(gc="Critical",dc=!0,bc+=Z/150):5>=I&&(gc="Deadly",dc=!0,bc+=Z/50)}
function rc(a){var b=.85*t,d=.45*q;c.lineWidth=2;c.textAlign="start";c.textBaseline="alphabetic";c.font="15px Arial";switch(a.a.type){case "SOLAR":var h=Tb*Math.max(.25,Math.sin(A*Math.PI/180));if(a.f&&I<X)I=Math.min(X,I+Z/1E3*h);else{var e=ub(a).filter(function(k){return null!=k.a.b}).filter(function(k){return k.a.b!=k.a.m}),p=h/e.length*(Z/1E3);e.forEach(function(k){k.a.b=k.a.b+p>=k.a.m?k.a.m:k.a.b+p})}a.f&&!Q&&(z("\u26a1",b+9,d+20),cb(b,d+40+.08*q,.1*q,Math.min(1,h/Tb)));break;case "CONSTRUCTOR":null!=
a.a.D&&a.a.T&&(a.a.K+=Z/1E4*Ub,1<=a.a.K&&(Xb?(pb(a.a.D.product),a.a.D=null,playerTile.a.K=0):a.a.N=!0,a.a.T=!1));a.f&&!Q&&(z("Recipe: "+(void 0!=a.a.D?a.a.D.product:"None"),b,d),z("\u26a1",b+9,d+20),a.a.N&&(c.fillStyle="#00FF00"),z("%",19+b+.025*q,d+20),cb(b,d+40+.08*q,.1*q,Math.min(1,a.a.b/a.a.m)),cb(10+b+.025*q,d+40+.08*q,.1*q,Math.min(1,a.a.K)));break;case "MINER":a.a.X?(a.a.M+=Z/25E3*Vb,1<=a.a.M&&(a.a.u=Math.min(a.a.W,a.a.u+5),fb(a),a.a.X=!1,a.a.M=0)):1<=a.a.b&&"NONE"!=a.i.type&&a.a.u<a.a.W&&
(--a.a.b,a.a.X=!0);Wb&&(a.a.u-=qb(a.a.O,a.a.u));a.f&&!Q&&(z("\u26a1",b+9,d+20),z("%",19+b+.025*q,d+20),z("\u2a06",29+b+.05*q,d+20),cb(b,d+40+.08*q,.1*q,Math.min(1,a.a.b/a.a.m)),cb(10+b+.025*q,d+40+.08*q,.1*q,Math.min(1,a.a.M)),cb(20+b+.05*q,d+40+.08*q,.1*q,Math.min(1,a.a.u/a.a.W)));break;case "BATTERY":e=ub(a).filter(function(k){return null!=k.a.b}).filter(function(k){return k.a.b!=k.a.m});var u=e.filter(function(k){return"BATTERY"==k.a.type}).filter(function(k){return k.a.b+1<a.a.b}),l=e.filter(function(k){return"BATTERY"!=
k.a.type});a.a.P?(a.a.L+=Z/1E4*Yb,0==e.length&&(a.a.L=0,a.a.P=!1,a.a.b=Math.min(a.a.b+1,a.a.m)),1<=a.a.L&&(a.a.L=0,a.a.P=!1,0<l.length?l.forEach(function(k){return k.a.b+=1/l.length}):0<u.length&&u.forEach(function(k){return k.a.b+=1/u.length}))):1<=a.a.b&&(0<l.length||0<u.length)&&(--a.a.b,a.a.P=!0);a.f&&!Q&&(z("\u26a1",b+9,d+20),z("%",19+b+.025*q,d+20),cb(b,d+40+.08*q,.1*q,Math.min(1,a.a.b/a.a.m)),cb(10+b+.025*q,d+40+.08*q,.1*q,Math.min(1,a.a.L)));break;case "RTG":a.f&&I<X?I=Math.min(X,I+Z/1E3*
Zb):(e=ub(a).filter(function(k){return null!=k.a.b}).filter(function(k){return k.a.b!=k.a.m}),p=Zb/e.length*(Z/1E3),e.forEach(function(k){k.a.b=k.a.b+p>=k.a.m?k.a.m:k.a.b+p}));break;case "GENERATOR":1<=a.a.J?(a.f&&I<X?I=Math.min(X,I+$b):(e=ub(a).filter(function(k){return null!=k.a.b}).filter(function(k){return k.a.b!=k.a.m}),p=$b/e.length,e.forEach(function(k){k.a.b=k.a.b+p>=k.a.m?k.a.m:k.a.b+p})),a.a.J=0,a.a.V=!1):1>a.a.J&&a.a.V?a.a.J+=Z/800:1<=a.a.I&&(a.f&&I<X||0<ub(a).filter(function(k){return null!=
k.a.b}).filter(function(k){return k.a.b!=k.a.m}).length)&&(--a.a.I,a.a.J=0,a.a.V=!0),a.f&&(z("\u2a06",b+9,d+20),z("%",19+b+.025*q,d+20),cb(b,d+40+.08*q,.1*q,Math.min(1,a.a.I/a.a.Z)),cb(10+b+.025*q,d+40+.08*q,.1*q,Math.min(1,a.a.J)))}}
document.addEventListener("keydown",function(a){switch(a.keyCode){case 87:K.h=!0;break;case 83:K.g=!0;break;case 68:K.right=!0;break;case 65:K.left=!0;break;case 69:K.c=!0;break;case 32:K.c=!0;break;case 66:K.F=!0;break;case 82:K.remove=!0;break;case 27:K.v=!0;break;case 16:K.G=!0}});
document.addEventListener("keyup",function(a){switch(a.keyCode){case 87:K.h=!1;break;case 83:K.g=!1;break;case 68:K.right=!1;break;case 65:K.left=!1;break;case 69:K.c=!1;break;case 32:K.c=!1;break;case 66:K.F=!1;break;case 82:K.remove=!1;break;case 27:K.v=!1;break;case 16:K.G=!1}});function C(a){zzfx.apply(null,ba(a)).start()}
setInterval(function(){Z=Q?0:(new Date).getTime()-mc;c.fillStyle="#000000";c.fillRect(0,0,Ra.clientWidth,Ra.clientHeight);Cb&&nc();if(lc){c.strokeStyle="#FFFFFF";c.fillStyle="#000000AA";tb(.02,.9,.1);var a=.13*t,b=.11*q;c.font="22px Arial";c.fillStyle="#FFFFFF";c.strokeStyle="#000000";c.textAlign="start";c.textBaseline="alphabetic";z("Welcome, valued Roboemployee, to the JMC\u2122 Autonomous Mining Initative.",a,b);z("Over the course of the next 7 solar rotations your mining effectiveness will be assesed by",
a,50+b);z("your ability to meet daily monetary quotas.",a,75+b);z("Quotas can be met by ",a,100+b);var d=c.measureText("Quotas can be met by ").width;c.fillStyle="#00FF00";z("Mining (E/Space)",a+d,100+b);d+=c.measureText("Mining (E/Space)").width;c.fillStyle="#FFFFFF";z(" and selling resources to the TELEDEPOT.",a+d,100+b);z("Failure to complete these quotas will result in immediate nuclear vapourisation.",a,150+b);z("JMC\u2122 Operations & Managment regrets to inform you that terrain maps",a,200+
b);z("for JMC\u2122 Planet 404 have been lost, you are required to use your",a,225+b);z("JMC\u2122 Craft's ",a,250+b);d=c.measureText("JMC\u2122 Craft's ").width;c.fillStyle="#00FF00";z("Build Mode (B) & Remove Mode (R)",a+d,250+b);d+=c.measureText("Build Mode (B) & Remove Mode (R)").width;c.fillStyle="#FFFFFF";z(" to place RADARs and uncover more terrain.",a+d,250+b);z("The CONSTRUCTOR creates buildings, such as extra RADARs, from resources and energy.",a,300+b);z("Your JMC\u2122 Craft has a limited battery capacity, failure to charge the battery",
a,325+b);z("will result in loss of resources and buildings in possesion.",a,350+b);z("An RTG has been made available to provide energy and charge your JMC\u2122 Craft.",a,375+b);z("A ROBOSHOP has been made available for you to purchase upgrades to aid effectiveness.",a,400+b);c.textAlign="center";z("WASD to move, left shift to sprint, E/Space to interact.",t/2,450+b);z("Good Luck.",t/2,.82*q);z("Press E/Space to start",t/2,25+.85*q);1==K.c&&0==J.c&&(lc=!1,kc=!0)}kc&&qc();J=Object.assign({},K);mc=
(new Date).getTime()},50);