function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}zzfx=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];return zzfxP(zzfxG.apply(null,ba(b)))};
zzfxP=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];c=zzfxX.createBufferSource();var h=zzfxX.createBuffer(b.length,b[0].length,zzfxR);b.map(function(m,g){return h.getChannelData(g).set(m)});c.buffer=h;c.connect(zzfxX.destination);return c};
zzfxG=function(a,b,c,h,m,g,y,la,L,ma,U,ra,za,Y,na,sa,Ca,ta,bb,B,V,ua,va,fa,O,H,wa,Z,Na,cb,tb,db,eb,E,fb,gb,I,Aa,Oa){a=void 0===a?1:a;b=void 0===b?.05:b;c=void 0===c?220:c;y=void 0===y?0:y;la=void 0===la?1:la;L=void 0===L?0:L;ma=void 0===ma?0:ma;U=void 0===U?0:U;ra=void 0===ra?0:ra;za=void 0===za?0:za;Y=void 0===Y?0:Y;na=void 0===na?0:na;sa=void 0===sa?0:sa;ta=void 0===ta?1:ta;B=void 0===B?zzfxR:B;V=void 0===V?99+(void 0===h?0:h)*B:V;ua=void 0===ua?(void 0===m?0:m)*B:ua;va=void 0===va?(void 0===g?
.1:g)*B:va;fa=void 0===fa?(void 0===bb?0:bb)*B:fa;O=void 0===O?(void 0===Ca?0:Ca)*B:O;H=void 0===H?2*Math.PI:H;wa=void 0===wa?function(Qb){return 0<Qb?1:-1}:wa;Z=void 0===Z?V+fa+ua+va+O:Z;Na=void 0===Na?L*=500*H/Math.pow(B,2):Na;cb=void 0===cb?c*=(1+2*b*Math.random()-b)*H/B:cb;tb=void 0===tb?wa(na)*H/4:tb;db=void 0===db?0:db;eb=void 0===eb?0:eb;E=void 0===E?0:E;fb=void 0===fb?0:fb;gb=void 0===gb?0:gb;I=void 0===I?0:I;Aa=void 0===Aa?1:Aa;for(Oa=void 0===Oa?[]:Oa;E<Z;Oa[E++]=I)++gb>100*sa&&(gb=0,I=
db*c*Math.sin(eb*na*H/B-tb),I=wa(I=y?1<y?2<y?3<y?Math.sin(Math.pow(I%H,3)):Math.max(Math.min(Math.tan(I),1),-1):1-(2*I/H%2+2)%2:1-4*Math.abs(Math.round(I/H)-I/H):Math.sin(I))*Math.pow(Math.abs(I),la)*a*zzfxV*(E<V?E/V:E<V+fa?1-(E-V)/fa*(1-ta):E<V+fa+ua?ta:E<Z-O?(Z-E-O)/va*ta:0),I=O?I/2+(O>E?0:(E<Z-O?1:(E-Z)/O)*Oa[E-O|0]/2):I),db+=1-Y+1E9*(Math.sin(E)+1)%2*Y,eb+=1-Y+1E9*(Math.pow(Math.sin(E),2)+1)%2*Y,c+=L+=500*ma*H/Math.pow(B,3),Aa&&++Aa>ra*B&&(c+=U*H/B,cb+=U*H/B,Aa=0),za&&++fb>za*B&&(c=cb,L=Na,fb=
1,Aa=Aa||1);return Oa};zzfxV=.5;zzfxR=44100;zzfxX=new (top.AudioContext||webkitAudioContext);
zzfxM=function(a,b,c,h){for(var m,g,y,la,L,ma,U,ra,za,Y,na,sa,Ca,ta,bb=0,B=[],V=[],ua=[],va=0,fa=0,O=1,H={},wa=zzfxR/(void 0===h?125:h)*60>>2;O;va++)B=[O=ra=sa=0],c.map(function(Z,Na){U=b[Z][va]||[0,0,0];O|=!!b[Z][va];ta=sa+(b[Z][0].length-2-!ra)*wa;Ca=Na==c.length-1;g=2;for(la=sa;g<U.length+Ca;ra=++g){L=U[g];za=g==U.length+Ca-1&&Ca||Y!=(U[0]||0)|L|0;for(y=0;y<wa&&ra;y++>wa-99&&za?na+=(1>na)/99:0)ma=(1-na)*B[bb++]/2||0,V[la]=(V[la]||0)-ma*fa+ma,ua[la]=(ua[la++]||0)+ma*fa+ma;L&&(na=L%1,fa=U[1]||0,
(L|=0)&&(B=H[[Y=U[bb=0]||0,L]]=H[[Y,L]]||(m=[].concat(ba(a[Y])),m[2]*=Math.pow(2,(L-12)/12),0<L?zzfxG.apply(null,ba(m)):[])))}sa=ta});return[V,ua]};function d(a){zzfx.apply(null,ba(a)).start()}function e(a){return Array.from(Array(a).keys())}var f=[e(18).map(function(a){return 2==a?15:0}),e(18).map(function(a){return 2==a?15:0}),e(18).map(function(a){return 10==a?15:0==a?1:0}),e(18).map(function(a){return 0==a?2:0==a%4&&12!=a?15:0})];f[1][14]=15;
function ca(a){return e(18).map(function(b){return 0==b?3:[2,6,10,14].includes(b)?a+[0,.1,.5,.7][[2,6,10,14].indexOf(b)]:1==b?-.1:0})}
var da=[ca(18),ca(22),ca(24),ca(30)],ea=e(32).map(function(a){return 8>a?a-4*Math.trunc(a/4):16>a?4+(a-4*Math.trunc(a/4)):8+(a-4*Math.trunc(a/4))}),ha=[[[,0,86,,,,,.7,,,,.5,,6.7,1,.05],[.7,0,270,,,.12,3,1.65,-2,,,,,4.5,,.02],[.4,0,2200,,,.04,3,2,,,800,.02,,4.8,,.01,.1],[,0,130.81,,,1]],[[da[0]],[da[1]],[da[2]],[da[3]],[da[0],f[0],f[2]],[da[1],f[0],f[2]],[da[2],f[0],f[2]],[da[3],f[1],f[2]],[da[0],f[0],f[2],f[3]],[da[1],f[0],f[2],f[3]],[da[2],f[0],f[2],f[3]],[da[3],f[1],f[2],f[3]]],ea,120];
function ia(a,b,c){this.x=a;this.y=b;this.z=c}function ja(a,b,c){return a.x*b+a.y*c}var ka=[new ia(1,1,0),new ia(-1,1,0),new ia(1,-1,0),new ia(-1,-1,0),new ia(1,0,1),new ia(-1,0,1),new ia(1,0,-1),new ia(-1,0,-1),new ia(0,1,1),new ia(0,-1,1),new ia(0,1,-1),new ia(0,-1,-1)],oa=e(256).map(function(){return Math.trunc(255*Math.random())}),pa=Array(512),qa=Array(512);
function xa(){var a=Math.random();a*=0<a&&1>a?65536:1;a=Math.floor(a);a=256>a?a|=a<<8:a;e(256).forEach(function(b){var c=b&1?oa[b]^a&255:oa[b]^a>>8&255;pa[b]=pa[b+256]=c;qa[b]=qa[b+256]=ka[c%12]})}function ya(a,b,c){return(1-c)*a+c*b}function Ba(a,b){var c=Math.floor(a),h=Math.floor(b);a-=c;b-=h;c&=255;h&=255;var m=a*a*a*(a*(6*a-15)+10);return ya(ya(ja(qa[c+pa[h]],a,b),ja(qa[c+1+pa[h]],a-1,b),m),ya(ja(qa[c+pa[h+1]],a,b-1),ja(qa[c+1+pa[h+1]],a-1,b-1),m),b*b*b*(b*(6*b-15)+10))}
function Da(a,b){this.x=a;this.y=b;this.l=!1;this.h={type:"NONE"};this.a={type:"NONE"};this.isVisible=!1;this.o={x:0,y:0};this.B=0}function k(a,b,c){this.r=a;this.P=b;this.N=c}function Ea(a){return"#"+Fa(a.r)+Fa(a.P)+Fa(a.N)+Fa(255)}function Ga(a,b){return new k(Math.min(255,Math.trunc(a.r*b)),Math.min(255,Math.trunc(a.P*b)),Math.min(255,Math.trunc(a.N*b)))}var Ha=document.getElementById("canv"),l=Ha.getContext("2d");l.imageSmoothingEnabled=!1;
var n=[],p=[],q,Ia=[{x:1,y:0},{x:.5,y:.866025},{x:-.5,y:.866025},{x:-1,y:0},{x:-.5,y:-.866025},{x:.5,y:-.866025}],r=1,t={x:0,y:0},Ja=new Map;Ja.set("NONE",new k(0,0,0));Ja.set("ROCK",new k(100,100,100));Ja.set("IRON",new k(165,42,42));Ja.set("COPPER",new k(184,115,51));Ja.set("CARBON",new k(18,18,18));Ja.set("LITHIUM",new k(169,169,169));Ja.set("SILICON",new k(0,153,204));Ja.set("PLUTONIUM",new k(0,255,0));var u=document.getElementById("0"),Ka=new Map;
Ka.set("RADAR",[document.getElementById("1"),.9]);Ka.set("CONSTRUCTOR",[document.getElementById("2"),.75]);Ka.set("SOLAR",[document.getElementById("3"),.5]);Ka.set("MINER",[document.getElementById("4"),.8]);Ka.set("RTG",[document.getElementById("5"),.75]);Ka.set("TELEDEPOT",[document.getElementById("6"),.75]);var La=new Map;La.set("Deadly",50);La.set("Critical",150);La.set("Very Low",400);
function Ma(a,b,c,h){h=void 0===h?!0:h;l.beginPath();l.moveTo(a[0].x+b,a[0].y+c);e(a.length-1).forEach(function(m){return l.lineTo(a[m+1].x+b,a[m+1].y+c)});l.closePath();h?l.fill():null;l.stroke()}function Pa(a){l.fillStyle="#FFFFF0";l.save();l.translate(v/2,w/2);l.rotate(a);Qa.forEach(function(b){l.beginPath();l.arc(b.x,b.y,b.r,0,2*Math.PI);l.fill()});l.restore()}
function Ra(){var a=n.filter(function(b){return"RADAR"==b.a.type});n.forEach(function(b){return b.isVisible=a.some(function(c){return Math.abs(c.x-b.x)<=Sa})})}function Ta(){function a(h,m){l.beginPath();l.arc(h,m,12.5,0,2*Math.PI);l.fill()}var b=.05*v,c=.07*w;l.save();l.translate(b,c);l.strokeStyle="#A2A2A2";Ma([{x:0,y:-25},{x:-25,y:25},{x:25,y:25}],0,0,!1);l.fillStyle="#FF0000";a(0,-25);l.fillStyle="#FFF500";a(-25,25);l.fillStyle="#0045FF";a(25,25);l.restore()}
function Ua(a,b,c,h){var m=.25*c;h=Math.min(1,h);l.save();l.translate(a,b);l.fillStyle=Ea(new k(255-255*h,255*h,0));l.fillRect(0,-c*h,m,c*h);l.strokeStyle="#FFFFFF";Ma([{x:0,y:-c},{x:m,y:-c},{x:m,y:0},{x:0,y:0}],0,0,!1);l.restore()}
function Va(a,b){Wa=0;q=null!=q?q:n.find(function(h){return h.l});var c=n.find(function(h){return h.x==q.x+a&&h.y==q.y+b});null!=c&&(c.isVisible?Math.abs(c.height-q.height)<=5*Xa?(q.l=!1,c.l=!0,t={x:q.o.x-c.o.x,y:q.o.y-c.o.y},q=c,d([x,.1,440,,,.07,,,,,50,.07])):p.push({text:"Incline too steep",time:0}):p.push({text:"Cannot enter unfound tile",time:0}))}function Ya(a){a.h=1==a.h.value?{type:"NONE"}:{type:a.h.type,value:a.h.value-1,lines:Za(a.h.value-1)}}
function $a(a,b){a.a.type=b.type;var c=a.a;switch(b.type){case "RADAR":Ra();break;case "CONSTRUCTOR":c.c=0;c.I=20;c.O=!1;c.u=0;c.J=!1;break;case "MINER":c.s=0,c.M=a.h.type,c.R=50,c.c=0,c.I=10,c.L=!1,c.u=0,c.counter=0}--b.value;d([x,,191,,,.07,1,1.09,-5.4,,,,,.4,-.4,.3,,.7])}function ab(){var a=q;hb(a.a.type);switch(a.a.type){case "RADAR":a.a={type:"NONE"};Ra();break;case "CONSTRUCTOR":a.a.J?hb(a.a.C.product):null}a.a={type:"NONE"};d([x,,400,,,.07,1,1.09,-5.4,,,,,.4,-.4,.3,,.7])}
function ib(a,b){var c=Math.min(jb,b),h=z.find(function(m){return m.type==a});null!=h?(h.value+c>jb&&(c=jb-h.value),h.value+=c):z.push({type:a,value:c});return c}function hb(a){var b=A.find(function(c){return c.type==a});null!=b?b.value+=1:A.push({type:a,value:1})}function kb(a){Ma(Ia.map(function(b){return{x:60*b.x,y:24*b.y}}),a.x,a.y)}function Fa(a){a=Math.trunc(a).toString(16);return 1==a.length?"0"+a:a}
function lb(){var a=55+25*z.length+.05*w;Ma([{x:0,y:.29*w},{x:.09*v,y:.29*w},{x:.1*v,y:.27*w},{x:.1*v,y:0},{x:0,y:0},{x:0,y:.48*w},{x:.09*v,y:.48*w},{x:.1*v,y:.46*w-.02},{x:.1*v,y:.29*w},{x:0,y:.29*w},{x:0,y:0},{x:.39*v,y:0},{x:.42*v,y:.04*w},{x:.58*v,y:.04*w},{x:.61*v,y:0},{x:.83*v,y:0},{x:.83*v,y:a-.02*w},{x:.85*v,y:a},{x:v,y:a},{x:v,y:0},{x:0,y:0}],0,0)}
function mb(a,b,c){var h=1-c;Ma([{x:v*(c+.04),y:w*a},{x:v*(h-.04),y:w*a},{x:v*h,y:w*(a+.04)},{x:v*h,y:w*(a+b-.04)},{x:v*(h-.04),y:w*(a+b)},{x:v*(c+.04),y:w*(a+b)},{x:v*c,y:w*(a+b-.04)},{x:v*c,y:w*(a+.04)}],0,0);a+=.02;b-=.04;Ma([{x:v*(c+.02+.04),y:w*a},{x:v*(h-.02-.04),y:w*a},{x:v*(h-.02),y:w*(a+.04)},{x:v*(h-.02),y:w*(a+b-.04)},{x:v*(h-.02-.04),y:w*(a+b)},{x:v*(c+.02+.04),y:w*(a+b)},{x:v*(c+.02),y:w*(a+b-.04)},{x:v*(c+.02),y:w*(a+.04)}],0,0)}
function nb(a){return n.filter(function(b){var c=b.y-a.y;b=b.x-a.x;return 1==Math.abs(c)&&0==b||0==c&&1==Math.abs(b)||0==a.x%2&&-1==c&&1==Math.abs(b)||0!=a.x%2&&1==c&&1==Math.abs(b)})}function Za(a){var b=5+Math.trunc(5*Math.random()),c=a/20,h=12*(Math.random()-.5)*c,m=12*(Math.random()-.5)*c;return e(b).map(function(g){return{x:Math.max(-31,Math.min(31,h+(Math.cos(2*Math.PI/b*g)*c*60+15*Math.random()*c))),y:Math.max(-19,Math.min(19,m+(Math.sin(2*Math.PI/b*g)*c*24+15*Math.random()*c*.4)))}})}
function ob(){n=e(pb).flatMap(function(a){return e(5).map(function(b){return new Da(a,b)})});n.forEach(function(a){var b=Math.max(0,Math.min(9,Math.trunc(Math.abs((Ba(a.x/10,a.y/10)+1)/2*9))));a.height=5*b;a.K=Ga(qb.find(function(h){return h.S.includes(b)}).K,1-(Math.random()-.5)/3);var c=Math.abs(rb-a.x);c>.005*pb&&.85<Math.random()?sb(a,"IRON",.4):null;c>.04*pb&&.9<Math.random()?sb(a,"COPPER",.5):null;c>.08*pb&&.92<Math.random()?sb(a,"CARBON",.6):null;c>.12*pb&&.92<Math.random()?sb(a,"SILICON",
.5):null;c>.14*pb&&.88<Math.random()?sb(a,"LITHIUM",.6):null;c>.24*pb&&.9<Math.random()?sb(a,"PLUTONIUM",.7):null;"PLUTONIUM"==a.h.type?ub(a,a.h.value):null});n.find(function(a){return a.x==rb}).l=!0;n.forEach(function(a){return"NONE"!=a.h.type?a.h.lines=Za(a.h.value):null})}
function sb(a,b,c){a.h={type:b,value:Math.max(10,Math.trunc(15*Math.random()))};nb(a).filter(function(){return Math.random()>c}).forEach(function(h){return h.h={type:b,value:Math.max(5,Math.trunc(a.h.value*Math.random()))}})}function ub(a,b){a.B=b;nb(a).forEach(function(c){return c.B=.8*b})}var vb="Resume;Main Menu;Save Game;Load Game;Mute Music;Mute Sound FX".split(";"),C=0,wb=["New Game","Load Game","Mute Music","Mute Sound FX"],xb=!0,x=0;
function yb(){d([x,.01,593,,.03,0,1,2.04,.1,.1,50,.01,,-.1,,,.06,.96,.08])}function zb(){d([x,0,604,,,.13,4,2.01,-.1,.2,50,,.01,,,.4,.05,.68,.05])}var Ab=[{product:"RADAR",items:[{type:"IRON",value:18}],c:8}];[{type:"ROCK",j:1},{type:"IRON",j:5},{type:"COPPER",j:25},{type:"CARBON",j:50},{type:"SILICON",j:80},{type:"LITHIUM",j:100},{type:"PLUTONIUM",j:200}];
var Bb=e(21).map(function(a){var b=Math.trunc(a/3),c=[{type:"ROCK",j:1},{type:"IRON",j:5},{type:"COPPER",j:25},{type:"CARBON",j:50},{type:"SILICON",j:80},{type:"LITHIUM",j:100},{type:"PLUTONIUM",j:200}][b];return{type:c.type,j:c.j,A:[1,10,50][a-3*b]}}),Cb=[{item:"RESOURCE STORAGE",i:350,F:2,m:["Increases max resource capacity","by 20%"]},{item:"BATTERY EFFICENCY",i:200,F:1.6,m:["Increases max battery capacity","by 25%"]},{item:"CRAFT HEIGHT TOLERANCE",i:350,F:1.5,m:["Allows passage between tiles with a",
"larger height difference."]},{item:"CONSTRUCTOR",i:500,m:["Allows construction of constructors.","Constructors manufacture other","buildings."]},{item:"MINER",i:750,m:["Allows construction of miners.","Miners gather resources 10 times","more efficent than manual mining."]},{item:"SOLAR",i:1250,m:["Allows construction of solars.","Solars generate fluctuating energy."]},{item:"RTG",i:2500,m:["Allows construction of RTGs.","RTGs generate constant energy."]},{item:"RADAR RADIUS",i:1E3,F:1.5,m:["Increases radar uncover",
"distance by 2 tiles."]},{item:"CONSTRUCTOR SPEED",i:200,F:1.8,m:["Increases constructor speed","by 30%"]},{item:"CONSTRUCTOR TRANSMITTER",i:1850,m:["Constructor transmits finished","constructions to inventory."]},{item:"MINER SPEED",i:750,F:1.8,m:["Incrases Miner speed by 50%"]},{item:"MINER TRANSMITTER",i:1985,m:["Miner transmits mined","resources to inventory."]},{item:"RTG OUTPUT",i:250,F:1.8,m:["Increases RTG output by 1."]},{item:"SOLAR OUTPUT",i:550,F:1.4,m:["Increases Solar output by 1."]}],
D,F,Db=1,G=50,Eb=50,Fb=!1,Gb,Hb=0,Ib=[500,1E3,2E3,5E3,1E4,2E4,5E4],Jb=!1,Kb=!1,v=1280,w=720;Ha.width=v;Ha.height=w;Ha.style.width=Ha.width+"px";Ha.style.height=Ha.height+"px";var J={g:!1,f:!1,left:!1,right:!1,b:!1,D:!1,remove:!1,v:!1,H:!1,G:!1},K={g:!1,f:!1,left:!1,right:!1,b:!1,D:!1,remove:!1,v:!1,H:!1,G:!1};n=[];p=[];var Lb=0,Mb=0,M=0,z,A,N=0,P=!1,Nb=!1,Q=!1,R=!1,Ob=!1,Pb=!1,S,Xa,jb,Rb,Sb,Tb,Ub,Vb,Wb,Sa,T,Xb,Yb=0,Zb=!1,$b=!1,Wa=0,ac="Nominal",bc=zzfxM.apply(null,ba(ha)),cc=zzfxP.apply(null,ba(bc));
cc.loop=!0;cc.start();var Qa=Array.from(Array(500).keys()).map(function(){return{x:2*Math.random()*v-v,y:2*Math.random()*w-w,r:3*Math.random()}}),pb=500,dc=new Map;dc.set(0,new k(80,81,79));dc.set(3,new k(242,95,92));dc.set(6,new k(255,224,102));dc.set(9,new k(36,123,160));var qb=e(4).map(function(a){return{S:[3*a,3*a+1,3*a+2],K:dc.get(3*a)}}),rb=240,ec=!1,fc=!1;function W(a,b,c){return l.fillText(a,b,c)}var gc=(new Date).getTime(),X=0;
function hc(){Pa(0);l.fillStyle="#FFFFFF";l.textAlign="center";l.textBaseline="middle";l.font="65px Tahoma";W("Planet 404",v/2,.1*w);1==K.g&&0==J.g&&(C=Math.max(0,C-1),d([]));1==K.f&&0==J.f&&(C=Math.min(wb.length-1,C+1),d([]));if(1==K.b&&0==J.b){switch(wb[C]){case "New Game":ic();x=.5;xb=!1;C=0;fc=!0;break;case "Load Game":null!=window.localStorage.getItem("Planet404_6473_DATA")&&(jc(),x=.5,ec=!0,xb=!1,C=0);break;case "Mute Music":cc.disconnect();wb[C]="Unmute Music";break;case "Mute Sound FX":x=
0;wb[C]="Unmute Sound FX";break;case "Unmute Music":cc.connect(zzfxX.destination);wb[C]="Mute Music";break;case "Unmute Sound FX":x=1,wb[C]="Mute Sound FX"}yb()}l.font="40px Tahoma";wb.forEach(function(a){l.fillStyle="#AAAAAA";C==wb.indexOf(a)&&(l.drawImage(u,Math.trunc(.45*v-.5*l.measureText(a).width-.5*u.width),Math.trunc(.3*w+80*wb.indexOf(a)-.5*u.height)),l.drawImage(u,Math.trunc(.55*v+.5*l.measureText(a).width-.5*u.width),Math.trunc(.3*w+80*wb.indexOf(a)-.5*u.height)),l.fillStyle="#FFFFFF");
W(a,.5*v,.3*w+80*wb.indexOf(a))})}
function ic(){xa();ob();A=[{type:"RADAR",value:1}];z=[];Gb=0;F=Ab.slice();D=Cb.slice();Pb=!1;G=S=50;Xa=1;jb=50;Rb=4;Tb=Sb=1;Vb=Ub=!1;Wb=5;Sa=6;Xb=T=0;Jb=!1;J={g:!1,f:!1,left:!1,right:!1,b:!1,D:!1,remove:!1,info:!1,v:!1,H:!1,G:!1};K={g:!1,f:!1,left:!1,right:!1,b:!1,D:!1,remove:!1,info:!1,v:!1,H:!1,G:!1};$a(n.find(function(a){return a.x==rb&&2==a.y}),{type:"RADAR",value:1});$a(n.find(function(a){return a.x==rb&&0==a.y}),{type:"RTG",value:1});$a(n.find(function(a){return a.x==rb-1&&0==a.y}),{type:"CONSTRUCTOR",
value:1});$a(n.find(function(a){return a.x==rb+2&&1==a.y}),{type:"TELEDEPOT",value:1});Va(0,0)}
function kc(){Pa(Math.PI/180*(360*Xb+T));n.filter(function(b){return 11>=Math.abs(b.x-q.x)}).sort(function(b,c){return b.height-c.height}).sort(function(b,c){return b.y-c.y}).sort(function(b,c){return b.isVisible-c.isVisible}).forEach(function(b){b.o.x=90*b.x+v/2-90*q.x;b.o.y=41.5692*b.y+.71*w+(0!=b.x%2?20.7846:0)-(b.isVisible?b.height:0);l.lineWidth=3;var c=new k(Math.max(0,b.K.r*(1-b.B/10)),Math.min(255,b.K.P*(1+b.B/10)),Math.max(0,b.K.N*(1-b.B/10)));l.strokeStyle=b.isVisible?0==b.B?Ea(Ga(c,.2)):
Ea(Ga(c,1.5)):"#000000";l.fillStyle=b.isVisible?Ea(c):"#AAAAAA";kb(b.o);c=Ja.get(b.h.type);l.fillStyle=Ea(c);l.strokeStyle=Ea(Ga(c,.2));b.isVisible&&"NONE"!=b.h.type?Ma(b.h.lines,b.o.x,b.o.y):null;l.fillStyle="#000000";l.font="24px Arial";l.textAlign="center";l.textBaseline="middle";b.isVisible?null:W("404",b.o.x,b.o.y);c=Ka.get(b.a.type);void 0!=c&&b.isVisible?l.drawImage(c[0],Math.trunc(b.o.x-c[0].width/2),Math.trunc(b.o.y-c[0].height*c[1])):null});var a=q.o;l.drawImage(u,Math.trunc(a.x-u.width*
r/2+t.x),Math.trunc(a.y-u.height*r/2-10+t.y+3*Math.sin(gc/400)),Math.trunc(u.width*r),Math.trunc(u.height*r));l.fillStyle="#FFFFFF";l.textAlign="center";if(!Q||Fb||Jb)if(Fb||Jb||Kb)Fb?(t.y=ya(t.y,10,X/1500),r=ya(r,0,X/1500),l.font=Math.trunc(50-50*r)+"px Arial",l.fillStyle="#FFFFFF",l.strokeStyle="#000000",l.textAlign="center",l.textBaseline="middle",W("You Died",v/2,.2*w),.4>r&&(W("Press E to respawn",v/2,.3*w),1==K.b&&0==J.b&&(G=S,z=[],A=[],Fb=!1,r=1,t={x:0,y:0}))):Jb?(t.y=ya(t.y,10,X/1500),r=ya(r,
0,X/1500),l.font=Math.trunc(50-50*r)+"px Arial",l.fillStyle="#FFFFFF",l.strokeStyle="#000000",l.textAlign="center",l.textBaseline="middle",W("Quota Failed",v/2,.2*w),n.forEach(function(b){return b.B=Math.min(6,b.B+X/800)}),.4>r&&(W("Press E to return to main menu",v/2,.3*w),1==K.b&&0==J.b&&(xb=!0,Jb=ec=Q=!1,r=1)),.8<r?(l.fillStyle="#FFFFFF"+Fa(255-(1-r)/.2*255),l.beginPath(),l.arc(v/2,w/2,(1-r)/.2*v,0,2*Math.PI),l.fill()):(l.fillStyle="#FFFFFF"+Fa(r/.8*255),l.fillRect(0,0,v,w))):Kb&&(l.strokeStyle=
"#FFFFFF",l.fillStyle="#000000AA",mb(.05,.5,.2),l.font="20px Arial",l.fillStyle="#FFFFFF",l.strokeStyle="#000000",l.textAlign="center",W("Congratulations, you have completed all JMC\u2122 Mining Initative quotas.",v/2,.2*w),W("Due to the costs of JMC\u2122 Craft recovery, you have been offered an",v/2,25+.2*w),W("involutary position as head of planetary excavations.",v/2,50+.2*w),W("Thanks for playing!",v/2,.45*w),1.5<=T&&(W("Press E to enter endless mode",v/2,25+.45*w),Pb=1==K.b&&0==J.b,Kb=!Pb));
else{n.filter(function(b){return b.isVisible&&"NONE"!=b.a.type}).forEach(function(b){return lc(b)});Db=1==K.H&&1==J.H?1.8:1;t={x:ya(t.x,0,X/180*Db),y:ya(t.y,0,X/180*Db)};z=z.filter(function(b){return 0<b.value});Lb=Math.min(Bb.filter(function(b){return z.some(function(c){return b.type==c.type&&c.value>=b.A})}).length-1,Lb);A=A.filter(function(b){return 0<b.value});M=Math.min(D.length-1,M);0==Bb.filter(function(b){return z.some(function(c){return b.type==c.type})&&R}).length&&(Lb=0,R=!1);if(Eb<G)Zb=
!1,ac="Charging";else if(R||["SOLAR","RTG"].some(function(b){return b==q.a.type}))Zb=!1,ac="Paused";G-=["Charging","Paused"].includes(ac)?0:X/1E3*(1+q.B);mc();nc()}else if(l.textBaseline="middle",l.font="45px Tahoma",W("Paused",v/2,30),l.font="35px Tahoma",vb.forEach(function(b){l.fillStyle="#AAAAAA";C==vb.indexOf(b)&&(l.drawImage(u,Math.trunc(.45*v-.5*l.measureText(b).width-.5*u.width),Math.trunc(.15*w+50*vb.indexOf(b)-.5*u.height)),l.drawImage(u,Math.trunc(.55*v+.5*l.measureText(b).width-.5*u.width),
Math.trunc(.15*w+50*vb.indexOf(b)-.5*u.height)),l.fillStyle="#FFFFFF");W(b,.5*v,.15*w+50*vb.indexOf(b))}),0==K.g&&1==J.g&&(C=Math.max(0,C-1),d([])),0==K.f&&1==J.f&&(C=Math.min(vb.length-1,C+1),d([])),1==K.v&&0==J.v&&(Q=!1),0==K.b&&1==J.b){switch(vb[C]){case "Resume":Q=!1;break;case "Main Menu":xb=!0;ec=Q=!1;break;case "Save Game":window.localStorage.setItem("Planet404_6473_DATA",JSON.stringify([n,T,Xb,z,A,Gb,G,F,D,S,Xa,jb,Sa,Rb,Sb,Tb,Ub,Vb,Wb,Pb]));p.push({text:"Game Saved",time:0});Q=!1;break;case "Load Game":null!=
window.localStorage.getItem("Planet404_6473_DATA")?jc():p.push({text:"Game Save not found",time:0});Q=!1;break;case "Mute Music":cc.disconnect();vb[C]="Unmute Music";break;case "Mute Sound FX":x=0;vb[C]="Unmute Sound FX";break;case "Unmute Music":cc.connect(zzfxX.destination);vb[C]="Mute Music";break;case "Unmute Sound FX":x=.5,vb[C]="Mute Sound FX"}yb()}0>=G&&!Fb&&(Fb=!0,d([x,,160,.01,.2,.04,2,,-.1,.1,-100,.1]));Eb=G;Fb||(T+=X/1500);359<T&&(Kb||Pb||(Gb>=Ib[Xb]?(Gb-=Ib[Xb],(Kb=6==Xb)?d([x,0,220,,
2,.08,1.5,,,,50,.07,.1,,,,.01]):d([x,0,160,,1,.04,2,,,,25,.07,.03,,,,.01])):(Jb=!0,d([x,,299,.01,.03,1.95,3,.1,.9,.6,,,,.5,.9,.6,,.52,.06]),d([x,0,160,,1.25,.04,2,,,,-25,.25,.01,,,,.01]))),Xb+=1,T=0)}
function nc(){P||Q||R||Ob||Nb?1==K.g&&0==J.g||1==K.f&&0==J.f?d([]):null:10>Math.abs(t.x)&&10>Math.abs(t.y)?1==K.g?Va(0,-1):1==K.f?Va(0,1):1==K.right?Va(1,0):1==K.left?Va(-1,0):null:null;P&&(N=1==K.g&&0==J.g?Math.max(0,N-1):1==K.f&&0==J.f?Math.min(A.length-1,N+1):N);Nb&&(N=1==K.g&&0==J.g?Math.max(0,N-1):1==K.f&&0==J.f?Math.min(F.length-1,N+1):N);R&&(Lb=1==K.g&&0==J.g?Math.max(0,Lb-1):1==K.f&&0==J.f?Math.min(Bb.filter(function(a){return z.some(function(b){return a.type==b.type&&b.value>=a.A})}).length-
1,Lb+1):Lb);Ob&&(M=1==K.g&&0==J.g?Math.max(0,M-1):1==K.f&&0==J.f?Math.min(D.length-1,M+1):M,1==K.b&&0==J.b?oc():null);1!=K.G||0!=J.G||P||Nb||R||(Ob=!Ob);1!=K.b||P||Q||Ob||(0==J.b&&(Wa=0),0==Wa&&("NONE"!=q.h.type&&"NONE"==q.a.type?(0<ib(q.h.type,1)?function(){Ya(q);d([x,.02,320,.01,,0,4,.1,,,,,,,,.2,.01,0,.01])}:function(){return p.push({text:"Resource full",time:0})})():"NONE"!=q.a.type&&pc()),Wa=1<=Wa?0:Wa+X/150);1!=K.D||0!=J.D||Nb||Q||R||Ob||(0<A.length&&!P?(N=0,P=!0):P?P=!1:p.push({text:"No Buildings",
time:0}));P&&1==K.b&&0==J.b&&n.some(function(a){return a.l&&"NONE"==a.a.type})&&($a(q,A[N]),P=!1,N=0);1==K.remove&&0==J.remove&&n.some(function(a){return a.l&&"NONE"!=a.a.type})?ab():null;1==K.v&&0==J.v&&(P||R||Ob||Nb?(Nb=Ob=R=P=!1,R=N=0):Q=!0)}
function jc(){Nb=Ob=R=P=!1;R=N=0;var a=JSON.parse(window.localStorage.getItem("Planet404_6473_DATA"));n=a[0];T=a[1];Xb=a[2];z=a[3];A=a[4];Gb=a[5];G=a[6];F=a[7];D=a[8];S=a[9];Xa=a[10];jb=a[11];Sa=a[12];Rb=a[13];Sb=a[14];Tb=a[15];Ub=a[16];Vb=a[17];Wb=a[18];Pb=a[19];Va(0,0)}
function oc(){if(Gb>=D[M].i){Gb-=D[M].i;D[M].i=null!=D[M].F?Math.round(D[M].i*D[M].F):D[M].i;var a=D[M].item;jb="RESOURCE STORAGE"==a?Math.round(1.2*jb):jb;S="BATTERY EFFICENCY"==a?1.25*S:S;Xa+="CRAFT HEIGHT TOLERANCE"==a?1:0;Sb="CONSTRUCTOR SPEED"==a?1.3*Sb:Sb;Vb="CONSTRUCTOR TRANSMITTER"==a;D="CONSTRUCTOR TRANSMITTER"==a?D.filter(function(b){return"CONSTRUCTOR TRANSMITTER"!=b.item}):D;Tb="MINER SPEED"==a?1.5*Tb:Tb;Ub="MINER TRANSMITTER"==a;D="MINER TRANSMITTER"==a?D.filter(function(b){return"MINER TRANSMITTER"!=
b.item}):D;Wb+="RTG OUTPUT"==a?1:0;Rb+="SOLAR OUTPUT"==a?1:0;Sa+="RADAR RADIUS"==a?2:0;"RADAR RADIUS"==a?Ra():null;"CONSTRUCTOR"==a?F.push({product:"CONSTRUCTOR",items:[{type:"IRON",value:10},{type:"COPPER",value:15}],c:4}):null;D="CONSTRUCTOR"==a?D.filter(function(b){return"CONSTRUCTOR"!=b.item}):D;"MINER"==a?F.push({product:"MINER",items:[{type:"IRON",value:10},{type:"COPPER",value:15},{type:"CARBON",value:8}],c:6}):null;D="MINER"==a?D.filter(function(b){return"MINER"!=b.item}):D;"SOLAR"==a?F.push({product:"SOLAR",
items:[{type:"COPPER",value:5},{type:"SILICON",value:10}],c:8}):null;D="SOLAR"==a?D.filter(function(b){return"SOLAR"!=b.item}):D;"RTG"==a?F.push({product:"RTG",items:[{type:"IRON",value:25},{type:"COPPER",value:25},{type:"PLUTONIUM",value:10}],c:10}):null;D="RTG"==a?D.filter(function(b){return"RTG"!=b.item}):D;yb()}else p.push({text:"Cannot afford "+D[M].item,time:0}),zb()}
function pc(){switch(q.a.type){case "CONSTRUCTOR":if(Nb)if(q.a.c>=F[N].c){var a=F[N].items;a.filter(function(h){return z.some(function(m){return m.type==h.type&&m.value>=h.value})}).length==a.length?(q.a.C=Object.assign({},F[N]),z.forEach(function(h){var m=a.find(function(g){return g.type==h.type});h.value-=null!=m?m.value:0}),p.push({text:"Crafting "+q.a.C.product,time:0}),q.a.O=!0,q.a.c-=F[N].c,Nb=!1,yb()):(p.push({text:"Missing resources",time:0}),zb())}else p.push({text:"Not enough energy",time:0});
else q.a.J?(hb(q.a.C.product),p.push({text:"Gained "+q.a.C.product,time:0}),q.a.J=!1,q.a.C=null,q.a.u=0,yb()):null==q.a.C&&(Nb=!0,N=0);break;case "MINER":if(!Ub&&0<q.a.s){var b=ib(q.a.M,q.a.s);0==b?(zb(),p.push({text:"Resource full",time:0})):(q.a.s-=ib(q.a.M,q.a.s),p.push({text:"Gained "+b+" "+q.a.M,time:0}),yb())}break;case "TELEDEPOT":if(R){var c=Bb.filter(function(h){return z.some(function(m){return h.type==m.type&&m.value>=h.A})||"EXIT"==h.type})[Lb];"EXIT"!=c.type?(b=z.find(function(h){return h.type==
c.type}),b.value>=c.A?(b.value-=c.A,Gb+=c.A*c.j,d([x,.01,287,.11,,0,3,.01,,,198,.09,,,,,.06,.5])):p.push({text:"Cannot sell "+c.A+" of "+c.type,time:0})):R=!1}else Lb=0,R=!0}}
function mc(){var a=.12*w;Zb?1<=Yb&&(d([x,0,500,.2,,0,1,.5,,,50,.12,,,,,,,.01]),$b=!$b,Yb=0):$b=!1;l.strokeStyle=$b?"#FF0000":"#FFFFFF";l.fillStyle="#000000AA";lb();l.font="15px Arial";l.fillStyle="#FFFFFF";l.textAlign="start";p=p.slice(-3,5);p=p.filter(function(g){return 2E3>g.time});var b=25*p.length;p.forEach(function(g){W(g.text,.01*v,.42*w+150-b+25*p.indexOf(g));g.time+=X});l.textAlign="center";l.textBaseline="middle";l.font="25px Arial";W("Inventory",.92*v,30);l.font="15px Arial";z.forEach(function(g){W(g.value+
"/"+jb+" units of "+g.type,.92*v,80+25*z.indexOf(g))});W("Sol: "+(Xb+1)+" Planet Rotation: "+T.toFixed(0)+"\u00b0",v/2,15);if(!(P||Nb||R||Ob)&&(5>=T||355<=T)){l.fillStyle="#000000AA";var c=Fa(255-255*Math.min(Math.abs(360-T),T)/5);l.strokeStyle="#FFFFFF"+c;mb(.05,.14,.39);l.font="30px Tahoma";l.fillStyle="#FFFFFF"+c;W("Sol "+(Xb+1)+"/7",v/2,a)}l.strokeStyle="#FFFFFF";if(P){l.fillStyle="#000000AA";mb(.05,.5,.4);l.font="30px Tahoma";l.fillStyle="#FFFFFF";W("Build Mode",v/2,a);l.font="20px Tahoma";var h=
A.filter(function(g){return Math.abs(A.indexOf(g)-N)<5+Math.max(0,4-N)});h.forEach(function(g){l.fillStyle=N==A.indexOf(g)?"#FFFFFF":"#AAAAAA";W(g.type+":"+g.value,v/2,a+40+25*h.indexOf(g))})}Nb&&(l.fillStyle="#000000AA",mb(.05,.5,.3),l.fillStyle="#FFFFFF",Ma([{x:.5*v,y:.07*w},{x:.5*v,y:.53*w}],0,0,!1),l.font="30px Tahoma",W("Set Recipe:",.4*v,a+.01*v),l.font="20px Tahoma",h=F.filter(function(g){return Math.abs(F.indexOf(g)-N)<5+Math.max(0,4-N)}),h.forEach(function(g){l.fillStyle=N==F.indexOf(g)?
"#FFFFFF":"#AAAAAA";"EXIT"!=g.product&&(N==F.indexOf(g)&&(l.font="25px Tahoma",g.items.forEach(function(y){return W(y.value+" "+y.type,.59*v,a+.01*v+40+25*g.items.indexOf(y))}),W(g.c+" ENERGY",.59*v,a+.01*v+40+25*g.items.length)),l.font="20px Tahoma");W(g.product,.4*v,a+.01*v+40+25*h.indexOf(g))}));if(R){l.fillStyle="#000000AA";mb(.05,.5,.4);l.fillStyle="#FFFFFF";l.font="30px Tahoma";W("Sell Mode",v/2,a);l.font="20px Tahoma";var m=Bb.filter(function(g){return z.some(function(y){return g.type==y.type&&
y.value>=g.A})||"EXIT"==g.type});h=m.filter(function(g){return Math.abs(m.indexOf(g)-Lb)<5+Math.max(0,4-Lb)});h.forEach(function(g){l.fillStyle=Lb==m.indexOf(g)?"#FFFFFF":"#AAAAAA";W("EXIT"!=g.type?g.A+" "+g.type+" : \u20bf"+g.j*g.A:g.type,v/2,a+40+25*h.indexOf(g))})}Ob&&(l.fillStyle="#000000AA",mb(.05,.5,.2),l.fillStyle="#FFFFFF",Ma([{x:.5*v,y:.07*w},{x:.5*v,y:.53*w}],0,0,!1),"EXIT"!=D[M].type?Ma([{x:.5*v,y:.46*w},{x:.78*v,y:.46*w}],0,0,!1):null,l.font="30px Tahoma",W("Buy Mode",.36*v,a),l.font=
"20px Tahoma",h=D.filter(function(g){return Math.abs(D.indexOf(g)-M)<5+Math.max(0,4-M)}),h.forEach(function(g){l.fillStyle=M==D.indexOf(g)?"#FFFFFF":"#AAAAAA";l.textAlign="center";W(g.item,.36*v,a+20+40+25*h.indexOf(g));M==D.indexOf(g)&&(W("\u20bf"+Mb.toLocaleString("en-US",{maximumFractionDigits:0}),.64*v,.495*w),l.textAlign="start",g.m.forEach(function(y){return W(y,.51*v,a+20+40+25*g.m.indexOf(y))}))}),Mb=ya(D[M].i,Mb,X/80));l.textAlign="center";l.textBaseline="middle";l.fillStyle="#FFFFFF";l.font=
"20px Tahoma";W("JMC",.05*v,.14*w);Ta();l.font="25px Tahoma";W("\u20bf"+Hb.toLocaleString("en-US",{maximumFractionDigits:0}),.05*v,.18*w);Hb=ya(Gb,Hb,X/100);l.font="20px Tahoma";(Pb?function(){W("Endless",.05*v,.22*w);W("Mode",.05*v,25+.22*w)}:function(){W("Daily Quota:",.05*v,.22*w);l.font="25px Tahoma";l.fillStyle=Gb>=Ib[Xb]?"#00FF00":300<T&&0==Math.trunc(T)%2?"#FF0000":"#FFFFFF";W("\u20bf"+Ib[Xb].toLocaleString("en-US",{maximumFractionDigits:0}),.05*v,.26*w)})();l.fillStyle="#FFFFFF";l.font="15px Tahoma";
Ua(.02*v,.45*w,100,G/S);l.fillStyle=$b?"#FF0000":"#FFFFFF";W("Battery",.07*v,.32*w);W("Status:",.07*v,.34*w);c=G/S;l.font="12px Tahoma";W(ac,.07*v,.36*w);l.fillStyle="#FFFFFF";0<n.find(function(g){return g.l}).B&&(l.font="50px Tahoma",W("\u2622",.07*v,w*(.45-.032)));ac=5>=G?"Deadly":10>=G?"Critical":15>=G?"Very Low":.6<c?"Nominal":.4<c?"Satisfactory":.3<c&&15<G?"Low":ac;Zb=La.has(ac);Yb+=Zb?X/La.get(ac):0}
function lc(a){var b=.85*v,c=.45*w;l.lineWidth=2;l.textAlign="start";l.textBaseline="alphabetic";l.font="15px Arial";switch(a.a.type){case "SOLAR":var h=Rb*Math.max(.5,Math.sin(T*Math.PI/180));G=a.l?Math.min(S,G+X/1E3*h):G;var m=nb(a).filter(function(g){return null!=g.a.c&&g.a.c!=g.a.I&&(!a.l||a.l!=G<S)});m.forEach(function(g){return g.a.c=Math.min(g.a.I,g.a.c+h/m.length*(X/1E3))});a.l&&!Q&&(W("\u26a1",b,c+20),Ua(b,c+40+.08*w,.1*w,h/Rb));break;case "CONSTRUCTOR":a.a.u+=a.a.O?X/1E4*Sb:0;1<=a.a.u&&
(a.a.O=!1,a.a.J=!0);Vb&&a.a.J&&(hb(a.a.C.product),a.a.C=null,a.a.u=0,a.a.J=!1);a.l&&!Q&&(W("Recipe: "+(void 0!=a.a.C?a.a.C.product:"None"),b,c),W("\u26a1",b,c+20),l.fillStyle=a.a.J?"#00FF00":l.fillStyle,W("%",b+12+.025*w,c+20),Ua(b,c+40+.08*w,.1*w,a.a.c/a.a.I),Ua(10+b+.025*w,c+40+.08*w,.1*w,a.a.u));break;case "MINER":!a.a.L&&1<=a.a.c&&"NONE"!=a.h.type&&a.a.s<a.a.R&&(--a.a.c,a.a.L=!0);a.a.u+=a.a.L?X/6E3*Tb:0;1<=a.a.u&&(a.a.s+=1,a.a.L=!1,a.a.u=0,a.counter+=1);10==a.counter&&(Ya(a),a.counter=0);a.a.s-=
Ub?ib(a.a.M,a.a.s):0;a.l&&!Q&&(W("\u26a1",b,c+20),W("%",12+b+.025*w,c+20),W("\u2a06",24+b+.05*w,c+20),Ua(b,c+40+.08*w,.1*w,Math.min(1,a.a.c/a.a.I)),Ua(10+b+.025*w,c+40+.08*w,.1*w,a.a.u),Ua(20+b+.05*w,c+40+.08*w,.1*w,a.a.s/a.a.R));break;case "RTG":G=a.l?Math.min(S,G+X/1E3*Wb):G,m=nb(a).filter(function(g){return null!=g.a.c&&g.a.c!=g.a.I&&(!a.l||a.l!=G<S)}),m.forEach(function(g){return g.a.c=Math.min(g.a.I,g.a.c+Wb/m.length*(X/1E3))})}}
document.addEventListener("keydown",function(a){a=a.keyCode;K.g=87==a?!0:K.g;K.f=83==a?!0:K.f;K.right=68==a?!0:K.right;K.left=65==a?!0:K.left;K.b=69==a?!0:K.b;K.D=66==a?!0:K.D;K.remove=82==a?!0:K.remove;K.v=27==a?!0:K.v;K.H=16==a?!0:K.H;K.G=81==a?!0:K.G});
document.addEventListener("keyup",function(a){a=a.keyCode;K.g=87==a?!1:K.g;K.f=83==a?!1:K.f;K.right=68==a?!1:K.right;K.left=65==a?!1:K.left;K.b=69==a?!1:K.b;K.D=66==a?!1:K.D;K.remove=82==a?!1:K.remove;K.v=27==a?!1:K.v;K.H=16==a?!1:K.H;K.G=81==a?!1:K.G});
setInterval(function(){X=Q?0:(new Date).getTime()-gc;l.fillStyle="#000000";l.fillRect(0,0,Ha.clientWidth,Ha.clientHeight);xb?hc():null;if(fc){Pa(0);l.strokeStyle="#FFFFFF";l.fillStyle="#000000AA";mb(.02,.9,.1);var a=.13*v,b=.11*w;l.font="22px Arial";l.fillStyle="#FFFFFF";l.strokeStyle="#000000";l.textAlign="start";l.textBaseline="alphabetic";W("Welcome, valued Roboemployee, to the JMC\u2122 Autonomous Mining Initative.",a,b);W("Over the course of the next 7 days your mining effectiveness will be assesed by",
a,50+b);W("your ability to meet daily monetary quotas.",a,75+b);W("Quotas can be met by mining and selling resources to the TELEDEPOT.",a,100+b);W("Failure to complete these quotas will result in immediate nuclear vapourisation.",a,150+b);W("JMC\u2122 Operations & Managment regrets to inform you that terrain maps",a,200+b);W("for JMC\u2122 Planet 404 have been lost, you are required to use RADARs and uncover more terrain.",a,225+b);W("Use the CONSTRUCTOR to create buildings, such as RADARs, from resources and energy.",
a,300+b);W("An RTG has been made available to provide energy and charge your JMC\u2122 Craft.",a,375+b);l.textAlign="center";W("WASD to move, left shift to sprint, E to interact/mine.",v/2,450+b);W("B to build, R to remove, Q to access upgrade shop",v/2,475+b);W("Good Luck.",v/2,.82*w);W("Press E to start",v/2,25+.85*w);1==K.b&&0==J.b&&(fc=!1,ec=!0)}else null;ec?kc():null;J=Object.assign({},K);l.fillStyle="#FFFFFF";W(X,200,50);gc=(new Date).getTime()},50);