function da(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ea(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:da(a)};for(var d=[];!(b=a.next()).done;)d.push(b.value);a=d}return a}zzfx=function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];return zzfxP(zzfxG.apply(null,ea(b)))};
zzfxP=function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];d=zzfxX.createBufferSource();var h=zzfxX.createBuffer(b.length,b[0].length,zzfxR);b.map(function(e,l){return h.getChannelData(l).set(e)});d.buffer=h;d.connect(zzfxX.destination);return d};
zzfxG=function(a,b,d,h,e,l,p,m,u,P,Z,na,za,ba,la,oa,Ha,pa,cb,K,aa,qa,ra,ia,V,Q,sa,ca,Oa,db,rb,eb,fb,N,gb,hb,R,Aa,Pa){a=void 0===a?1:a;b=void 0===b?.05:b;d=void 0===d?220:d;p=void 0===p?0:p;m=void 0===m?1:m;u=void 0===u?0:u;P=void 0===P?0:P;Z=void 0===Z?0:Z;na=void 0===na?0:na;za=void 0===za?0:za;ba=void 0===ba?0:ba;la=void 0===la?0:la;oa=void 0===oa?0:oa;pa=void 0===pa?1:pa;K=void 0===K?zzfxR:K;aa=void 0===aa?99+(void 0===h?0:h)*K:aa;qa=void 0===qa?(void 0===e?0:e)*K:qa;ra=void 0===ra?(void 0===l?
.1:l)*K:ra;ia=void 0===ia?(void 0===cb?0:cb)*K:ia;V=void 0===V?(void 0===Ha?0:Ha)*K:V;Q=void 0===Q?2*Math.PI:Q;sa=void 0===sa?function(Tb){return 0<Tb?1:-1}:sa;ca=void 0===ca?aa+ia+qa+ra+V:ca;Oa=void 0===Oa?u*=500*Q/Math.pow(K,2):Oa;db=void 0===db?d*=(1+2*b*Math.random()-b)*Q/K:db;rb=void 0===rb?sa(la)*Q/4:rb;eb=void 0===eb?0:eb;fb=void 0===fb?0:fb;N=void 0===N?0:N;gb=void 0===gb?0:gb;hb=void 0===hb?0:hb;R=void 0===R?0:R;Aa=void 0===Aa?1:Aa;for(Pa=void 0===Pa?[]:Pa;N<ca;Pa[N++]=R)++hb>100*oa&&(hb=
0,R=eb*d*Math.sin(fb*la*Q/K-rb),R=sa(R=p?1<p?2<p?3<p?Math.sin(Math.pow(R%Q,3)):Math.max(Math.min(Math.tan(R),1),-1):1-(2*R/Q%2+2)%2:1-4*Math.abs(Math.round(R/Q)-R/Q):Math.sin(R))*Math.pow(Math.abs(R),m)*a*zzfxV*(N<aa?N/aa:N<aa+ia?1-(N-aa)/ia*(1-pa):N<aa+ia+qa?pa:N<ca-V?(ca-N-V)/ra*pa:0),R=V?R/2+(V>N?0:(N<ca-V?1:(N-ca)/V)*Pa[N-V|0]/2):R),eb+=1-ba+1E9*(Math.sin(N)+1)%2*ba,fb+=1-ba+1E9*(Math.pow(Math.sin(N),2)+1)%2*ba,d+=u+=500*P*Q/Math.pow(K,3),Aa&&++Aa>na*K&&(d+=Z*Q/K,db+=Z*Q/K,Aa=0),za&&++gb>za*K&&
(d=db,u=Oa,gb=1,Aa=Aa||1);return Pa};zzfxV=.5;zzfxR=44100;zzfxX=new (top.AudioContext||webkitAudioContext);
zzfxM=function(a,b,d,h){for(var e,l,p,m,u,P,Z,na,za,ba,la,oa,Ha,pa,cb=0,K=[],aa=[],qa=[],ra=0,ia=0,V=1,Q={},sa=zzfxR/(void 0===h?125:h)*60>>2;V;ra++)K=[V=na=oa=0],d.map(function(ca,Oa){Z=b[ca][ra]||[0,0,0];V|=!!b[ca][ra];pa=oa+(b[ca][0].length-2-!na)*sa;Ha=Oa==d.length-1;l=2;for(m=oa;l<Z.length+Ha;na=++l){u=Z[l];za=l==Z.length+Ha-1&&Ha||ba!=(Z[0]||0)|u|0;for(p=0;p<sa&&na;p++>sa-99&&za?la+=(1>la)/99:0)P=(1-la)*K[cb++]/2||0,aa[m]=(aa[m]||0)-P*ia+P,qa[m]=(qa[m++]||0)+P*ia+P;u&&(la=u%1,ia=Z[1]||0,(u|=
0)&&(K=Q[[ba=Z[cb=0]||0,u]]=Q[[ba,u]]||(e=[].concat(ea(a[ba])),e[2]*=Math.pow(2,(u-12)/12),0<u?zzfxG.apply(null,ea(e)):[])))}oa=pa});return[aa,qa]};function c(a){zzfx.apply(null,ea(a)).start()}function fa(a){return Array.from(Array(a).keys())}var f=[fa(18).map(function(a){return 2==a?15:0}),fa(18).map(function(a){return 2==a?15:0}),fa(18).map(function(a){return 10==a?15:0==a?1:0}),fa(18).map(function(a){return 0==a?2:0==a%4&&12!=a?15:0})];f[1][14]=15;
function ha(a){return fa(18).map(function(b){return 0==b?3:[2,6,10,14].includes(b)?a+[0,.1,.5,.7][[2,6,10,14].indexOf(b)]:1==b?-.1:0})}
var ja=[ha(18),ha(22),ha(24),ha(30)],ka=[8,9,10,11,8,9,10,11],ma=[[[,0,86,,,,,.7,,,,.5,,6.7,1,.05],[.7,0,270,,,.12,3,1.65,-2,,,,,4.5,,.02],[.4,0,2200,,,.04,3,2,,,800,.02,,4.8,,.01,.1],[,0,130.81,,,1]],[[ja[0]],[ja[1]],[ja[2]],[ja[3]],[ja[0],f[0],f[2]],[ja[1],f[0],f[2]],[ja[2],f[0],f[2]],[ja[3],f[1],f[2]],[ja[0],f[0],f[2],f[3]],[ja[1],f[0],f[2],f[3]],[ja[2],f[0],f[2],f[3]],[ja[3],f[1],f[2],f[3]]],[0,1,2,3,0,1,2,3,4,5,6,7,4,5,6,7].concat(ka,ka,ka,ka),120];
function ta(a,b,d){this.x=a;this.y=b;this.z=d}function ua(a,b,d){return a.x*b+a.y*d}var va=[new ta(1,1,0),new ta(-1,1,0),new ta(1,-1,0),new ta(-1,-1,0),new ta(1,0,1),new ta(-1,0,1),new ta(1,0,-1),new ta(-1,0,-1),new ta(0,1,1),new ta(0,-1,1),new ta(0,1,-1),new ta(0,-1,-1)],wa=fa(256).map(function(){return Math.trunc(255*Math.random())}),xa=Array(512),ya=Array(512);
function Ba(a){0<a&&1>a&&(a*=65536);a=Math.floor(a);256>a&&(a|=a<<8);for(var b=0;256>b;b++){var d=b&1?wa[b]^a&255:wa[b]^a>>8&255;xa[b]=xa[b+256]=d;ya[b]=ya[b+256]=va[d%12]}}Ba(0);function Ca(a,b,d){return(1-d)*a+d*b}function Da(a,b){var d=Math.floor(a),h=Math.floor(b);a-=d;b-=h;d&=255;h&=255;var e=a*a*a*(a*(6*a-15)+10);return Ca(Ca(ua(ya[d+xa[h]],a,b),ua(ya[d+1+xa[h]],a-1,b),e),Ca(ua(ya[d+xa[h+1]],a,b-1),ua(ya[d+1+xa[h+1]],a-1,b-1),e),b*b*b*(b*(6*b-15)+10))}
function Ea(a,b){this.x=a;this.y=b;this.h=!1;this.i={type:"NONE"};this.a={type:"NONE"};this.isVisible=!1;this.l={x:0,y:0};this.C=0}function g(a,b,d,h){this.r=a;this.R=b;this.O=d;this.T=h}function Fa(a){return"#"+Ga(a.r)+Ga(a.R)+Ga(a.O)+Ga(a.T)}function Ia(a,b){return new g(Math.min(255,Math.trunc(a.r*b)),Math.min(255,Math.trunc(a.R*b)),Math.min(255,Math.trunc(a.O*b)),a.T)}var Ja=document.getElementById("canv"),k=Ja.getContext("2d");k.imageSmoothingEnabled=!1;
var n=[],q=[],Ka=[{x:1,y:0},{x:.5,y:.866025},{x:-.5,y:.866025},{x:-1,y:0},{x:-.5,y:-.866025},{x:.5,y:-.866025}],r=1,La=new Map;La.set("ROCK",new g(100,100,100,255));La.set("IRON",new g(165,42,42,255));La.set("COPPER",new g(184,115,51,255));La.set("CARBON",new g(18,18,18,255));La.set("LITHIUM",new g(169,169,169,255));La.set("SILICON",new g(0,153,204,255));La.set("PLUTONIUM",new g(0,255,0,255));var t=document.getElementById("0"),Ma=new Map;Ma.set("RADAR",{G:document.getElementById("1"),K:.9});
Ma.set("CONSTRUCTOR",{G:document.getElementById("2"),K:.6});Ma.set("SOLAR",{G:document.getElementById("3"),K:.5});Ma.set("MINER",{G:document.getElementById("4"),K:.6});Ma.set("RTG",{G:document.getElementById("5"),K:.8});Ma.set("TELEDEPOT",{G:document.getElementById("6"),K:.6});Ma.set("ROBOSHOP",{G:document.getElementById("7"),K:.6});
function Na(){var a=.71*v,b=w,d=n.find(function(e){return e.h});n.filter(function(e){return 11>=Math.abs(e.x-d.x)}).sort(function(e,l){return e.height-l.height}).sort(function(e,l){return e.y-l.y}).sort(function(e,l){return e.isVisible-l.isVisible}).forEach(function(e){e.l.x=90*e.x+x/2-90*d.x;e.l.y=41.5692*e.y+a+(0!=e.x%2?20.7846:0);k.lineWidth=3;if(e.isVisible){e.l.y-=e.height;var l=new g(Math.max(0,e.J.r*(1-e.C/10)),Math.min(255,e.J.R*(1+e.C/10)),Math.max(0,e.J.O*(1-e.C/10)),255);k.strokeStyle=
0==e.C?Fa(Ia(l,.2)):Fa(Ia(l,1.5));k.fillStyle=Fa(l);Qa(e.l);if("NONE"!=e.i.type){l=La.get(e.i.type);k.lineWidth=3;k.fillStyle=Fa(l);k.strokeStyle=Fa(Ia(l,.4));l=e.i.lines;k.beginPath();k.moveTo(l[0].x+e.l.x,l[0].y+e.l.y);for(var p=1;p<l.length;p++)k.lineTo(l[p].x+e.l.x,l[p].y+e.l.y);k.closePath();k.fill();k.stroke()}l=Ma.get(e.a.type);void 0!=l?k.drawImage(l.G,Math.trunc(e.l.x-l.G.width/2),Math.trunc(e.l.y-l.G.height*l.K)):null}else k.strokeStyle="#000000",k.fillStyle="#AAAAAA",Qa(e.l),k.fillStyle=
"#000000",k.font="24px Arial",k.textAlign="center",k.textBaseline="middle",y("404",e.l.x,e.l.y)});var h=d.l;k.drawImage(t,Math.trunc(h.x-t.width*r/2+b.x),Math.trunc(h.y-t.height*r/2-10+b.y+5*Math.sin(Ra/500)),Math.trunc(t.width*r),Math.trunc(t.height*r))}function Sa(){var a=n.filter(function(b){return"RADAR"==b.a.type});n.forEach(function(b){return b.isVisible=a.some(function(d){return Math.abs(d.x-b.x)<=Ta})})}
function Ua(){var a=.05*x,b=.07*v;k.save();k.translate(a,b);k.strokeStyle="#A2A2A2";k.beginPath();k.moveTo(0,-25);k.lineTo(-25,25);k.lineTo(25,25);k.closePath();k.stroke();k.fillStyle="#FF0000";k.beginPath();k.arc(0,-25,12.5,0,2*Math.PI);k.fill();k.fillStyle="#FFF500";k.beginPath();k.arc(-25,25,12.5,0,2*Math.PI);k.fill();k.fillStyle="#0045FF";k.beginPath();k.arc(25,25,12.5,0,2*Math.PI);k.fill();k.restore()}
function Va(a,b,d,h){var e=.25*d;h=Math.min(1,h);k.save();k.translate(a,b);k.fillStyle=Fa(new g(255-255*h,255*h,0,255));k.fillRect(0,-d*h,e,d*h);k.strokeStyle="#FFFFFF";k.beginPath();k.moveTo(0,-d);k.lineTo(e,-d);k.lineTo(e,0);k.lineTo(0,0);k.closePath();k.stroke();k.restore()}
function Wa(a,b){z=0;var d=n.find(function(e){return e.h}),h=n.find(function(e){return e.x==d.x+a&&e.y==d.y+b});null!=h&&(h.isVisible?Math.abs(h.height-d.height)<=5*Xa?(d.h=!1,h.h=!0,w={x:d.l.x-h.l.x,y:d.l.y-h.l.y},c([A,.1,440,,,.07,,,,,50,.07])):q.push({text:"Incline too steep",time:0}):q.push({text:"Cannot enter unfound tile",time:0}))}function Ya(a){1==a.i.value?a.i={type:"NONE"}:(--a.i.value,a.i.lines=Za(a.i.value))}
function $a(a,b){a.a.type=b.type;var d=a.a;switch(b.type){case "RADAR":Sa();break;case "CONSTRUCTOR":d.b=0;d.H=20;d.P=!1;d.u=0;d.L=!1;break;case "MINER":d.s=0,d.N=a.i.type,d.U=50,d.b=0,d.H=10,d.S=!1,d.u=0,d.counter=0}--b.value;c([A,,191,,,.07,1,1.09,-5.4,,,,,.4,-.4,.3,,.7])}
function ab(a){switch(a.a.type){case "RADAR":var b=n.find(function(d){return d.h});if(0==n.filter(function(d){return Math.abs(d.x-b.x)<=Ta&&"RADAR"==d.a.type&&d!=a}).length){q.push({text:"No other radar in range",time:0});return}bb(a.a.type);a.a={type:"NONE"};Sa();break;case "CONSTRUCTOR":1==a.a.L&&bb(a.a.D.product);bb(a.a.type);break;default:bb(a.a.type)}a.a={type:"NONE"};c([A,,400,,,.07,1,1.09,-5.4,,,,,.4,-.4,.3,,.7])}
function ib(a,b){var d=Math.min(jb,b),h=B.find(function(e){return e.type==a});null!=h?(h.value+d>jb&&(d=jb-h.value),h.value+=d):B.push({type:a,value:d});return d}function bb(a){var b=C.find(function(d){return d.type==a});null!=b?b.value+=1:C.push({type:a,value:1})}function Qa(a){k.beginPath();k.moveTo(a.x+60*Ka[0].x,a.y+24*Ka[0].y);Ka.slice(1,Ka.length).forEach(function(b){return k.lineTo(a.x+60*b.x,a.y+24*b.y)});k.closePath();k.fill();k.stroke()}
function Ga(a){a=Math.trunc(a).toString(16);return 1==a.length?"0"+a:a}
function kb(){var a=55+25*B.length+.05*v,b=[];b.unshift({x:0,y:.29*v});b.unshift({x:.09*x,y:.29*v});b.unshift({x:.1*x,y:.27*v});b.unshift({x:.1*x,y:0});b.unshift({x:0,y:0});b.unshift({x:0,y:.48*v});b.unshift({x:.09*x,y:.48*v});b.unshift({x:.1*x,y:.46*v-.02});b.unshift({x:.1*x,y:.29*v});b.unshift({x:0,y:.29*v});b.unshift({x:0,y:0});b.unshift({x:.39*x,y:0});b.unshift({x:.42*x,y:.04*v});b.unshift({x:.58*x,y:.04*v});b.unshift({x:.61*x,y:0});b.unshift({x:.83*x,y:0});b.unshift({x:.83*x,y:a-.02*v});b.unshift({x:.85*
x,y:a});b.unshift({x:x,y:a});b.unshift({x:x,y:0});b.unshift({x:0,y:0});return b}
function lb(a,b,d){var h=1-d;k.beginPath();k.moveTo(x*(d+.04),v*a);k.lineTo(x*(h-.04),v*a);k.lineTo(x*h,v*(a+.04));k.lineTo(x*h,v*(a+b-.04));k.lineTo(x*(h-.04),v*(a+b));k.lineTo(x*(d+.04),v*(a+b));k.lineTo(x*d,v*(a+b-.04));k.lineTo(x*d,v*(a+.04));k.closePath();k.fill();k.stroke();a+=.02;b-=.04;k.beginPath();k.moveTo(x*(d+.02+.04),v*a);k.lineTo(x*(h-.02-.04),v*a);k.lineTo(x*(h-.02),v*(a+.04));k.lineTo(x*(h-.02),v*(a+b-.04));k.lineTo(x*(h-.02-.04),v*(a+b));k.lineTo(x*(d+.02+.04),v*(a+b));k.lineTo(x*
(d+.02),v*(a+b-.04));k.lineTo(x*(d+.02),v*(a+.04));k.closePath();k.fill();k.stroke()}function mb(a){return n.filter(function(b){var d=b.y-a.y;b=b.x-a.x;return 1==Math.abs(d)&&0==b||0==d&&1==Math.abs(b)||0==a.x%2&&-1==d&&1==Math.abs(b)||0!=a.x%2&&1==d&&1==Math.abs(b)})}
function Za(a){var b=5+Math.trunc(5*Math.random());a/=20;for(var d=12*(Math.random()-.5)*a,h=12*(Math.random()-.5)*a,e=[],l=0;l<b;l++){var p=2*Math.PI/b*l;e.unshift({x:Math.max(-31,Math.min(31,d+(Math.cos(p)*a*60+15*Math.random()*a))),y:Math.max(-19,Math.min(19,h+(Math.sin(p)*a*24+15*Math.random()*a*.4)))})}return e}
function nb(){var a=ob;n=fa(500).flatMap(function(b){return fa(5).map(function(d){return new Ea(b,d)})});n.forEach(function(b){var d=Math.max(0,Math.min(10,Math.trunc(Math.abs((Da(b.x/10,b.y/10)+1)/2*10))));b.height=5*d;b.J=Ia(a.find(function(h){return h.M.includes(d)}).J,1-(Math.random()-.5)/3);2.5<Math.abs(240-b.x)&&.85<Math.random()?pb(b,"IRON",.4):25<Math.abs(240-b.x)&&.9<Math.random()?pb(b,"COPPER",.5):40<Math.abs(240-b.x)&&.92<Math.random()?pb(b,"CARBON",.6):60<Math.abs(240-b.x)&&.96<Math.random()?
pb(b,"SILICON",.5):70<Math.abs(240-b.x)&&.85<Math.random()?pb(b,"LITHIUM",.6):120<Math.abs(240-b.x)&&.85<Math.random()?(pb(b,"PLUTONIUM",.7),qb(b,4)):.88<Math.random()&&pb(b,"ROCK",.9);80<Math.abs(240-b.x)&&.95<Math.random()&&qb(b,5*Math.random())});n.find(function(b){return 240==b.x}).h=!0;n.filter(function(b){return"NONE"!=b.i.type}).forEach(function(b){return b.i.lines=Za(b.i.value)})}
function pb(a,b,d){a.i={type:b,value:Math.max(10,Math.trunc(15*Math.random()))};mb(a).filter(function(){return Math.random()>d}).forEach(function(h){return h.i={type:b,value:Math.max(5,Math.trunc(a.i.value*Math.random()))}})}function qb(a,b){a.C=b;mb(a).forEach(function(d){return d.C=.8*b})}var sb="Resume;Main Menu;Save Game;Load Game;Mute Music;Mute Sound FX".split(";"),D=0,tb=["New Game","Load Game","Mute Music","Mute Sound FX"],ub=!0,A=0;
function vb(){zzfx.apply(null,[A,.01,593,,.03,0,1,2.04,.1,.1,50,.01,,-.1,,,.06,.96,.08]).start()}function wb(){zzfx.apply(null,[A,0,604,,,.13,4,2.01,-.1,.2,50,,.01,,,.4,.05,.68,.05]).start()}
var xb=[{product:"EXIT",items:[],b:0},{product:"RADAR",items:[{type:"IRON",value:18}],b:8}],yb=[{type:"ROCK",A:1},{type:"IRON",A:5},{type:"COPPER",A:25},{type:"CARBON",A:50},{type:"SILICON",A:80},{type:"LITHIUM",A:100},{type:"PLUTONIUM",A:200}],zb=fa(21).map(function(a){var b=Math.trunc(a/3),d=yb[b];return{type:d.type,A:d.A,o:[1,10,50][a-3*b]}});zb.unshift({type:"EXIT",A:0,o:0});
var Ab=[{type:"EXIT",item:"EXIT",j:0,B:0,m:[]},{type:"CRAFT UPGRADES",item:"RESOURCE STORAGE",j:350,B:2,m:["Increases JMC\u2122 Craft resource","capacity by 20%"]},{type:"CRAFT UPGRADES",item:"BATTERY EFFICENCY",j:200,B:1.6,m:["Increases JMC\u2122 Craft battery capacity","by 25%"]},{type:"CRAFT UPGRADES",item:"CRAFT HEIGHT TOLERANCE",j:350,B:1.5,m:["Allows JMC\u2122 Craft to","move between tiles","with a larger height","difference."]},{type:"RECIPES",item:"CONSTRUCTOR",j:500,m:["Adds JMC\u2122 Constructor to",
"Constructor Database.","Constructors manufacture other","JMC\u2122 Buildings."]},{type:"RECIPES",item:"MINER",j:750,m:"Adds JMC\u2122 Miner to Constructor;Database.;JMC\u2122 Miners use energy to;gather resources 10 times;more efficent than;the JMC\u2122 Craft".split(";")},{type:"RECIPES",item:"SOLAR",j:1250,m:["Adds JMC\u2122 Solar Panel to","Constructor Database.","JMC\u2122 Solar Panels generate","fluctuating energy."]},{type:"RECIPES",item:"RTG",j:2500,m:["Adds JMC\u2122 RTG to","Constructor Database.",
"JMC\u2122 RTGs generate","constant energy."]},{type:"BUILDING UPGRADES",item:"RADAR RADIUS",j:1E3,B:1.5,m:["Increases JMC\u2122 Radar uncover","distance by 3 tiles."]},{type:"BUILDING UPGRADES",item:"CONSTRUCTOR SPEED",j:200,B:1.8,m:["Increases JMC\u2122 Constructor speed","by 30%"]},{type:"BUILDING UPGRADES",item:"CONSTRUCTOR TRANSMITTER",j:1850,m:["JMC\u2122 Constructor transmits","finished constructions to","JMC\u2122 Craft."]},{type:"BUILDING UPGRADES",item:"MINER SPEED",j:750,B:1.8,m:["Increases JMC\u2122 Miner speed",
"by 50%"]},{type:"BUILDING UPGRADES",item:"MINER TRANSMITTER",j:1985,m:["JMC\u2122 Miner transmits","mined resources to","JMC\u2122 Craft."]},{type:"BUILDING UPGRADES",item:"RTG OUTPUT",j:250,B:1.8,m:["Increases JMC\u2122 RTG output","by 1."]},{type:"BUILDING UPGRADES",item:"SOLAR OUTPUT",j:750,B:1.4,m:["Increases JMC\u2122 Solar Panel output","by 1."]}],E=Ab.slice(),Bb=xb.slice(),Cb=1,F=50,Db=50,Eb=!1,Fb,Gb=0,Hb=[500,1E3,2E3,5E3,1E4,2E4,5E4],Ib=!1,Jb=!1,x=1280,v=720;Ja.width=x;Ja.height=v;
Ja.style.width=Ja.width+"px";Ja.style.height=Ja.height+"px";var G={g:!1,f:!1,left:!1,right:!1,c:!1,F:!1,remove:!1,v:!1,I:!1},H={g:!1,f:!1,left:!1,right:!1,c:!1,F:!1,remove:!1,v:!1,I:!1},w={x:0,y:0};n=[];q=[];var I=0,Kb=0,J=0,B,C,L=0,M=!1,O=!1,S=!1,T=!1,U=!1,Lb=!1,Mb,Xa,jb,Nb,Ob,Pb,Qb,Rb,Sb,Ta,W,X,Ub=0,Vb=!1,Wb=!1,z=0,Xb=1,Yb="Nominal",Zb=zzfxM.apply(null,ea(ma)),$b=zzfxP.apply(null,ea(Zb));$b.loop=!0;$b.start();
var ac=Array.from(Array(500).keys()).map(function(){return{x:2*Math.random()*x-x,y:2*Math.random()*v-v,r:3*Math.random()}});Ba(Math.random());var ob=[{M:[0,1,2],J:new g(62,47,91,255)},{M:[3,4],J:new g(190,184,235,255)},{M:[5,6,7],J:new g(64,121,140,255)},{M:[8,9,10],J:new g(115,251,211,255)}],bc=!1,cc=!1;function y(a,b,d){return k.fillText(a,b,d)}var Ra=(new Date).getTime(),Y=0;
function dc(){k.fillStyle="#FFFFF0";k.save();k.translate(x/2,v/2);ac.forEach(function(a){k.beginPath();k.arc(a.x,a.y,a.r,0,2*Math.PI);k.fill()});k.restore();k.fillStyle="#FFFFFF";k.textAlign="center";k.textBaseline="middle";k.font="65px Tahoma";y("Planet 404",x/2,.1*v);1==H.g&&0==G.g&&(D=Math.max(0,D-1),c([]));1==H.f&&0==G.f&&(D=Math.min(tb.length-1,D+1),c([]));if(1==H.c&&0==G.c){switch(tb[D]){case "New Game":ec();A=.5;ub=!1;D=0;cc=!0;break;case "Load Game":null!=window.localStorage.getItem("Planet404_6473_DATA")&&
(fc(),A=.5,bc=!0,ub=!1,D=0);break;case "Mute Music":$b.disconnect();tb[D]="Unmute Music";break;case "Mute Sound FX":A=0;tb[D]="Unmute Sound FX";break;case "Unmute Music":$b.connect(zzfxX.destination);tb[D]="Mute Music";break;case "Unmute Sound FX":A=1,tb[D]="Mute Sound FX"}vb()}k.font="40px Tahoma";tb.forEach(function(a){var b=tb.indexOf(a);if(D==b){var d=k.measureText(a).width;k.drawImage(t,Math.trunc(.45*x-.5*d-.5*t.width),Math.trunc(.3*v+80*b-.5*t.height));k.drawImage(t,Math.trunc(.55*x+.5*d-.5*
t.width),Math.trunc(.3*v+80*b-.5*t.height));k.fillStyle="#FFFFFF"}else k.fillStyle="#AAAAAA";y(a,.5*x,.3*v+80*b)})}
function ec(){nb();Wa(0,0);C=[{type:"RADAR",value:1}];B=[];Fb=0;Bb=xb.slice();E=Ab.slice();Lb=!1;F=Mb=50;Xa=1;jb=50;Nb=2;Pb=Ob=1;Rb=Qb=!1;Sb=5;Ta=6;X=W=0;Ib=!1;G={g:!1,f:!1,left:!1,right:!1,c:!1,F:!1,remove:!1,info:!1,v:!1,I:!1};H={g:!1,f:!1,left:!1,right:!1,c:!1,F:!1,remove:!1,info:!1,v:!1,I:!1};$a(n.find(function(a){return 240==a.x&&2==a.y}),{type:"RADAR",value:1});$a(n.find(function(a){return 240==a.x&&0==a.y}),{type:"RTG",value:1});$a(n.find(function(a){return 239==a.x&&0==a.y}),{type:"CONSTRUCTOR",
value:1});$a(n.find(function(a){return 243==a.x&&2==a.y}),{type:"TELEDEPOT",value:1});$a(n.find(function(a){return 237==a.x&&1==a.y}),{type:"ROBOSHOP",value:1})}
function gc(){k.fillStyle="#FFFFF0";k.save();k.translate(x/2,v/2);k.rotate(Math.PI/180*(360*X+W));ac.forEach(function(d){k.beginPath();k.arc(d.x,d.y,d.r,0,2*Math.PI);k.fill()});k.restore();Na();k.fillStyle="#FFFFFF";k.textAlign="center";if(!S||Eb||Ib)if(Eb||Ib||Jb)if(Eb){w.y=Ca(w.y,10,Y/1500);r=Ca(r,0,Y/1500);var b=Math.trunc(50-50*r);k.font=b+"px Arial";k.fillStyle="#FFFFFF";k.strokeStyle="#000000";k.textAlign="center";k.textBaseline="middle";y("You Died",x/2,.2*v);.4>r&&(y("Press E/Space to respawn",
x/2,.3*v),1==H.c&&0==G.c&&(F=Mb,B=[],C=[],n.find(function(d){return d.h}).h=!1,n.find(function(d){return 240==d.x}).h=!0,Wa(0,0),Eb=!1,r=1,w={x:0,y:0}))}else Ib?(w.y=Ca(w.y,10,Y/1500),r=Ca(r,0,Y/1500),b=Math.trunc(50-50*r),k.font=b+"px Arial",k.fillStyle="#FFFFFF",k.strokeStyle="#000000",k.textAlign="center",k.textBaseline="middle",y("Quota Failed",x/2,.2*v),n.forEach(function(d){return d.C=Math.min(6,d.C+Y/800)}),.4>r&&(y("Press E to return to main menu",x/2,.3*v),1==H.c&&0==G.c&&(ub=!0,Ib=bc=S=
!1,r=1)),.8<r?(k.fillStyle="#FFFFFF"+Ga(255-(1-r)/.2*255),k.beginPath(),k.arc(x/2,v/2,(1-r)/.2*x,0,2*Math.PI),k.fill()):(k.fillStyle="#FFFFFF"+Ga(r/.8*255),k.fillRect(0,0,x,v))):Jb&&(k.strokeStyle="#FFFFFF",k.fillStyle="#000000A",lb(.05,.5,.2),b=x/2*.45,k.font="20px Arial",k.fillStyle="#FFFFFF",k.strokeStyle="#000000",k.textAlign="start",k.textBaseline="alphabetic",y("Congratulations, you have completed all JMC\u2122 Mining Initative quotas.",b,.2*v),y("Due to the costs of JMC\u2122 Craft recovery, you have been offered an",
b,25+.2*v),y("involutary position as cheif of planetary excavations and are forbidden",b,50+.2*v),y("from leaving this planet.",b,75+.2*v),k.textAlign="center",y("Thanks for playing!",x/2,.45*v),1.5<=W&&(y("Press E to enter endless mode",x/2,25+.45*v),1==H.c&&0==G.c&&(Lb=!0,Jb=!1)));else{n.filter(function(d){return d.isVisible&&"NONE"!=d.a.type}).forEach(function(d){return hc(d)});w.x=Ca(w.x,0,Y/150*Cb);w.y=Ca(w.y,0,Y/150*Cb);1==H.I&&0==G.I?Cb=1.8:0==H.I&&1==G.I&&(Cb=1);B=B.filter(function(d){return 0<
d.value});I=Math.min(zb.filter(function(d){return B.some(function(h){return d.type==h.type&&h.value>=d.o})||"EXIT"==d.type}).length-1,I);C=C.filter(function(d){return 0<d.value});J=Math.min(E.length-1,J);T&&0==zb.filter(function(d){return B.some(function(h){return d.type==h.type&&h.value>=d.o})}).length&&(I=0,T=!1);var a=n.find(function(d){return d.h});Db<F?(Vb=!1,Yb="Charging"):T||U||["SOLAR","RTG"].some(function(d){return d==a.a.type})?(Vb=!1,Yb="Paused"):F-=Y/1E3*(1+a.C);ic();jc()}else if(k.textBaseline=
"middle",k.font="45px Tahoma",y("Paused",x/2,30),k.font="35px Tahoma",sb.forEach(function(d){var h=sb.indexOf(d);if(D==h){var e=k.measureText(d).width;k.drawImage(t,Math.trunc(.45*x-.5*e-.5*t.width),Math.trunc(.15*v+50*h-.5*t.height));k.drawImage(t,Math.trunc(.55*x+.5*e-.5*t.width),Math.trunc(.15*v+50*h-.5*t.height));k.fillStyle="#FFFFFF"}else k.fillStyle="#AAAAAA";y(d,.5*x,.15*v+50*h)}),0==H.g&&1==G.g&&(D=Math.max(0,D-1),c([])),0==H.f&&1==G.f&&(D=Math.min(sb.length-1,D+1),c([])),1==H.v&&0==G.v&&
(S=!1),0==H.c&&1==G.c){switch(sb[D]){case "Resume":S=!1;break;case "Main Menu":ub=!0;bc=S=!1;break;case "Save Game":window.localStorage.setItem("Planet404_6473_DATA",JSON.stringify([n,W,X,B,C,Fb,F,Bb,E,Mb,Xa,jb,Ta,Nb,Ob,Pb,Qb,Rb,Sb,Lb]));q.push({text:"Game Saved",time:0});S=!1;break;case "Load Game":null!=window.localStorage.getItem("Planet404_6473_DATA")?fc():q.push({text:"Game Save not found",time:0});S=!1;break;case "Mute Music":$b.disconnect();sb[D]="Unmute Music";break;case "Mute Sound FX":A=
0;sb[D]="Unmute Sound FX";break;case "Unmute Music":$b.connect(zzfxX.destination);sb[D]="Mute Music";break;case "Unmute Sound FX":A=1,sb[D]="Mute Sound FX"}vb()}0>=F&&!Eb&&(Eb=!0,c([A,,160,.01,.2,.04,2,,-.1,.1,-100,.1]));Db=F;Eb||(W+=Y/1500);359<=W&&(Fb>=Hb[X]&&!Jb&&!Lb?(Fb-=Hb[X],X==Hb.length-1?(Jb=!0,c([A,0,220,,2,.08,1.5,,,,50,.07,.1,,,,.01])):c([A,0,160,,1,.04,2,,,,25,.07,.03,,,,.01])):Jb||Lb||Ib||(Ib=!0,c([A,,299,.01,.03,1.95,3,.1,.9,.6,,,,.5,.9,.6,,.52,.06]),c([A,0,160,,1.25,.04,2,,,,-25,.25,
.01,,,,.01])),X+=1);W=359<=W?0:W}
function jc(){!(1!=H.g||0!=G.g||M||O||S||T||U)&&10>Math.abs(w.y)&&Wa(0,-1);!(1!=H.f||0!=G.f||M||O||S||T||U)&&10>Math.abs(w.y)&&Wa(0,1);!(1!=H.g||1!=G.g||M||O||S||T||U)&&10>Math.abs(w.y)&&Wa(0,-1);!(1!=H.f||1!=G.f||M||O||S||T||U)&&10>Math.abs(w.y)&&Wa(0,1);1==H.g&&0==G.g&&M&&(L=Math.max(0,L-1),c([]));1==H.f&&0==G.f&&M&&(L=Math.max(0,Math.min(C.length-1,L+1)),c([]));1==H.g&&0==G.g&&O&&(L=Math.max(0,L-1),c([]));1==H.f&&0==G.f&&O&&(L=Math.max(0,Math.min(Bb.length-1,L+1)),c([]));1==H.g&&0==G.g&&T&&(z=
0,I=Math.max(0,I-1),c([]));1==H.f&&0==G.f&&T&&(z=0,I=Math.min(zb.filter(function(b){return B.some(function(d){return b.type==d.type&&d.value>=b.o})||"EXIT"==b.type}).length-1,I+1),c([]));1==H.g&&0==G.g&&U&&(z=0,J=Math.max(0,J-1),c([]));1==H.f&&0==G.f&&U&&(z=0,J=Math.min(E.length-1,J+1),c([]));1==H.g&&1==G.g&&T&&(1<=z?(I=Math.max(0,I-1),z=0,c([])):z+=Y/100);1==H.f&&1==G.f&&T&&(1<=z?(I=Math.min(zb.filter(function(b){return B.some(function(d){return b.type==d.type&&d.value>=b.o})||"EXIT"==b.type}).length-
1,I+1),z=0,c([])):z+=Y/100);1==H.g&&1==G.g&&U&&(1<=z?(J=Math.max(0,J-1),z=0,c([])):z+=Y/100);1==H.f&&1==G.f&&U&&(1<=z?(J=Math.min(E.length-1,J+1),z=0,c([])):z+=Y/100);!(1!=H.right||0!=G.right||M||S||T||U)&&10>Math.abs(w.x)&&Wa(1,0);!(1!=H.left||0!=G.left||M||S||T||U)&&10>Math.abs(w.x)&&Wa(-1,0);!(1!=H.right||1!=G.right||M||S||T||U)&&10>Math.abs(w.x)&&Wa(1,0);!(1!=H.left||1!=G.left||M||S||T||U)&&10>Math.abs(w.x)&&Wa(-1,0);if(1==H.c&&0==G.c&&!M&&!S){Xb=1;z=0;var a=n.find(function(b){return b.h});"NONE"!=
a.a.type?kc(a):"NONE"!=a.i.type&&(0<ib(a.i.type,1)?(Ya(a),c([A,0,320,.01,,0,4,.1,,,,,,,,.2,.01,0,.01])):q.push({text:"Resource full",time:0}))}a=n.find(function(b){return b.h});1==H.c&&1==G.c&&!M&&!S&&1<=z?(z=0,a=n.find(function(b){return b.h}),"NONE"!=a.a.type?kc(a):"NONE"!=a.i.type&&(0<ib(a.i.type,1)?(Ya(a),c([A,0,320,.01,,0,4,.1,,,,,,,,.2,.01,0,.01])):q.push({text:"Resource full",time:0}))):1!=H.c||1!=G.c||M||S||(z+=Y/100*Xb);1!=H.F||0!=G.F||M||O||S||T||U?1==H.F&&0==G.F&&M&&(M=!1):0<C.length?(L=
0,M=!0):q.push({text:"No Buildings",time:0});a=n.find(function(b){return b.h});M&&1==H.c&&0==G.c&&n.some(function(b){return b.h&&"NONE"==b.a.type})&&($a(a,C[L]),C=C.filter(function(b){return 0<b.value}),M=!1,L=0);1==H.remove&&0==G.remove&&n.some(function(b){return b.h&&"NONE"!=b.a.type})&&ab(a);1==H.v&&0==G.v&&(M||T||U||O)?(O=U=T=M=!1,T=L=0):1==H.v&&0==G.v&&(S=!0)}
function fc(){O=U=T=M=!1;T=L=0;var a=JSON.parse(window.localStorage.getItem("Planet404_6473_DATA"));n=a[0];W=a[1];X=a[2];B=a[3];C=a[4];Fb=a[5];F=a[6];Bb=a[7];E=a[8];Mb=a[9];Xa=a[10];jb=a[11];Ta=a[12];Nb=a[13];Ob=a[14];Pb=a[15];Qb=a[16];Rb=a[17];Sb=a[17];Lb=a[18];Wa(0,0)}
function kc(a){switch(a.a.type){case "CONSTRUCTOR":if(O){var b=Object.assign({},Bb[L]);if("EXIT"!=b.product)if(a.a.b>=b.b){var d=b.items;d.filter(function(e){return B.some(function(l){return l.type==e.type&&l.value>=e.value})}).length==d.length?(a.a.D=b,B.forEach(function(e){var l=d.find(function(p){return p.type==e.type});null!=l&&(e.value-=l.value,q.push({text:"Used "+l.value+" units of "+e.type,time:0}))}),a.a.P=!0,a.a.b-=b.b,vb()):(d.forEach(function(e){var l=B.find(function(p){return p.type==
e.type&&p.value<e.value});null!=l?q.push({text:e.value-l.value+" more "+e.type+" needed",time:0}):B.some(function(p){return p.type==e.type})||q.push({text:e.value+" more "+e.type+" needed",time:0})}),wb())}else q.push({text:"Not enough energy",time:0});O=!1}else a.a.L?(bb(a.a.D.product),q.push({text:"Gained "+a.a.D.product,time:0}),a.a.L=!1,a.a.D=null,a.a.u=0,vb()):null==a.a.D&&(O=!0,L=0);break;case "MINER":!Qb&&0<a.a.s&&(b=ib(a.a.N,a.a.s),0==b?(wb(),q.push({text:"Resource full",time:0})):(a.a.s-=
ib(a.a.N,a.a.s),q.push({text:"Gained "+b+" "+a.a.N,time:0}),vb()));break;case "TELEDEPOT":if(T){var h=zb.filter(function(e){return B.some(function(l){return e.type==l.type&&l.value>=e.o})||"EXIT"==e.type})[I];"EXIT"!=h.type?(a=B.find(function(e){return e.type==h.type}),a.value>=h.o?(a.value-=h.o,Fb+=h.o*h.A,c([A,.01,287,.11,,0,3,.01,,,198,.09,,,,,.06,.5])):q.push({text:"Cannot sell "+h.o+" of "+h.type,time:0})):(I=0,T=!1)}else I=0,T=!0;break;case "ROBOSHOP":if(U)if("EXIT"!=E[J].type)if(Fb>=E[J].j){Fb-=
E[J].j;switch(E[J].item){case "RESOURCE STORAGE":jb=Math.round(1.2*jb);break;case "BATTERY EFFICENCY":Mb=Math.round(1.25*Mb);break;case "CRAFT HEIGHT TOLERANCE":Xa+=1;break;case "CONSTRUCTOR SPEED":Ob*=1.3;break;case "CONSTRUCTOR TRANSMITTER":Rb=!0;E=E.filter(function(e){return"CONSTRUCTOR TRANSMITTER"!=e.item});break;case "MINER SPEED":Pb*=1.5;break;case "MINER TRANSMITTER":Qb=!0;E=E.filter(function(e){return"MINER TRANSMITTER"!=e.item});break;case "RTG OUTPUT":Sb+=1;break;case "SOALR OUTPUT":Nb+=
1;break;case "RADAR RADIUS":Ta+=3;Sa();break;case "CONSTRUCTOR":Bb.push({product:"CONSTRUCTOR",items:[{type:"IRON",value:10},{type:"COPPER",value:15}],b:4});E=E.filter(function(e){return"CONSTRUCTOR"!=e.item});break;case "MINER":Bb.push({product:"MINER",items:[{type:"IRON",value:10},{type:"COPPER",value:15},{type:"CARBON",value:8}],b:6});E=E.filter(function(e){return"MINER"!=e.item});break;case "SOLAR":Bb.push({product:"SOLAR",items:[{type:"COPPER",value:5},{type:"SILICON",value:10}],b:8});E=E.filter(function(e){return"SOLAR"!=
e.item});break;case "RTG":Bb.push({product:"RTG",items:[{type:"IRON",value:25},{type:"COPPER",value:25},{type:"PLUTONIUM",value:10}],b:10}),E=E.filter(function(e){return"RTG"!=e.item})}null!=E[J].B&&(E[J].j=Math.round(E[J].j*E[J].B));vb()}else q.push({text:"Cannot afford "+E[J].item,time:0}),wb();else U=!1;else U=!0}}
function ic(){var a=.12*v;Vb?1<=Ub&&(c([A,0,500,.2,,0,1,.5,,,50,.12,,,,,,,.01]),Wb=!Wb,Ub=0):Wb=!1;k.strokeStyle=Wb?"#FF0000":"#FFFFFF";k.fillStyle="#000000AA";var b=kb();k.beginPath();for(var d=0;d<b.length;d++)0==d?k.moveTo(b[d].x,b[d].y):k.lineTo(b[d].x,b[d].y);k.closePath();k.fill();k.stroke();k.font="15px Arial";k.fillStyle="#FFFFFF";k.textAlign="start";q=q.slice(-3,5);q=q.filter(function(m){return 2E3>m.time});var h=25*q.length;q.forEach(function(m){y(m.text,.01*x,.42*v+150-h+25*q.indexOf(m));
m.time+=Y});k.textAlign="center";k.textBaseline="middle";k.font="25px Arial";y("Inventory",.92*x,30);k.font="15px Arial";B.forEach(function(m){y(m.value+"/"+jb+" units of "+m.type,.92*x,80+25*B.indexOf(m))});y("Sol: "+(X+1)+" Planet Rotation: "+W.toFixed(0)+"\u00b0",x/2,15);M||O||T||U||!(8>=W||352<=W)||(k.fillStyle="#000000AA",3>W||357<=W?(k.strokeStyle="#FFFFFF",lb(.05,.14,.39),k.font="30px Tahoma",k.fillStyle="#FFFFFF",y("Sol "+(X+1)+"/7",x/2,a)):8>=W?(b=Ga(255-(W-3)/5*255),k.strokeStyle="#FFFFFF"+
b,lb(.05,.14,.39),k.font="30px Tahoma",k.fillStyle="#FFFFFF"+b,y("Sol "+(X+1)+"/7",x/2,a)):352<=W&&(b=Ga((W-352)/5*255),k.strokeStyle="#FFFFFF"+b,lb(.05,.14,.39),k.font="30px Tahoma",k.fillStyle="#FFFFFF"+b,y("Sol "+(X+1)+"/7",x/2,a)));k.strokeStyle="#FFFFFF";if(M){k.fillStyle="#000000AA";lb(.05,.5,.4);k.font="30px Tahoma";k.fillStyle="#FFFFFF";y("Build Mode",x/2,a);k.font="20px Tahoma";var e=5,l=C.filter(function(m){return Math.abs(C.indexOf(m)-L)<e+Math.max(0,e-1-L)});l.forEach(function(m){var u=
C.indexOf(m);k.fillStyle="#AAAAAA";L==u&&(k.fillStyle="#FFFFFF");"EXIT"!=m.type?y(m.value+" "+m.type,x/2,a+40+25*l.indexOf(m)):y(m.type,x/2,a+40+25*l.indexOf(m))})}O&&(k.fillStyle="#000000AA",lb(.05,.5,.3),k.fillStyle="#FFFFFF",k.beginPath(),k.moveTo(.5*x,.07*v),k.lineTo(.5*x,.53*v),k.stroke(),k.font="30px Tahoma",y("Set Recipe:",.4*x,a+.01*x),k.font="20px Tahoma",e=5,l=Bb.filter(function(m){return Math.abs(Bb.indexOf(m)-L)<e+Math.max(0,e-1-L)}),l.forEach(function(m){var u=Bb.indexOf(m);k.fillStyle=
"#AAAAAA";L==u&&(k.fillStyle="#FFFFFF");"EXIT"!=m.product&&(L==u&&(k.font="25px Tahoma",m.items.forEach(function(P){return y(P.value+" "+P.type,.59*x,a+.01*x+40+25*m.items.indexOf(P))}),y(m.b+" ENERGY",.59*x,a+.01*x+40+25*m.items.length)),k.font="20px Tahoma");y(m.product,.4*x,a+.01*x+40+25*l.indexOf(m))}));if(T){k.fillStyle="#000000AA";lb(.05,.5,.4);k.fillStyle="#FFFFFF";k.font="30px Tahoma";y("Sell Mode",x/2,a);k.font="20px Tahoma";e=5;var p=zb.filter(function(m){return B.some(function(u){return m.type==
u.type&&u.value>=m.o})||"EXIT"==m.type});l=p.filter(function(m){return Math.abs(p.indexOf(m)-I)<e+Math.max(0,e-1-I)});l.forEach(function(m){var u=p.indexOf(m);k.fillStyle="#AAAAAA";I==u&&(k.fillStyle="#FFFFFF");"EXIT"!=m.type?y(m.o+" "+m.type+" : \u20bf"+m.A*m.o,x/2,a+40+25*l.indexOf(m)):y(m.type,x/2,a+40+25*l.indexOf(m))})}U&&(k.fillStyle="#000000AA",lb(.05,.5,.2),k.fillStyle="#FFFFFF",k.beginPath(),k.moveTo(.5*x,.07*v),k.lineTo(.5*x,.53*v),k.stroke(),"EXIT"!=E[J].type&&(k.beginPath(),k.moveTo(.5*
x,.46*v),k.lineTo(.78*x,.46*v),k.stroke()),k.font="30px Tahoma",y("Buy Mode",.36*x,a),k.font="20px Tahoma",e=5,l=E.filter(function(m){return Math.abs(E.indexOf(m)-J)<e+Math.max(0,e-1-J)}),l.forEach(function(m){var u=E.indexOf(m);k.fillStyle="#AAAAAA";J==u&&(k.fillStyle="#FFFFFF");k.textAlign="center";k.textBaseline="middle";"EXIT"!=m.type?(y(m.item,.36*x,a+20+40+25*l.indexOf(m)),J==u&&(y(m.type,.65*x,a+20),y("\u20bf"+Kb.toLocaleString("en-US",{maximumFractionDigits:0}),.64*x,.495*v),k.textAlign="start",
m.m.forEach(function(P){return y(P,.51*x,a+20+40+25*m.m.indexOf(P))}))):y(m.type,.36*x,a+20+40+25*l.indexOf(m))}),Kb=Ca(E[J].j,Kb,Y/80));k.textAlign="center";k.textBaseline="middle";k.fillStyle="#FFFFFF";k.font="20px Tahoma";y("JMC",.05*x,.14*v);Ua();Lb?(y("Endless",.05*x,.22*v),y("Mode",.05*x,25+.22*v)):y("Daily Quota:",.05*x,.22*v);k.font="25px Tahoma";y("\u20bf"+Gb.toLocaleString("en-US",{maximumFractionDigits:0}),.05*x,.18*v);Gb=Ca(Fb,Gb,Y/100);Lb||(Fb>=Hb[X]?k.fillStyle="#00FF00":300<W&&0==Math.trunc(W)%
2&&(k.fillStyle="#FF0000"),y("\u20bf"+Hb[X].toLocaleString("en-US",{maximumFractionDigits:0}),.05*x,.26*v));k.fillStyle="#FFFFFF";k.font="15px Tahoma";Va(.02*x,.45*v,100,F/Mb);Wb&&(k.fillStyle="#FF0000");y("Battery",.07*x,.32*v);y("Status:",.07*x,.34*v);b=F/Mb;k.font="12px Tahoma";y(Yb,.07*x,.36*v);k.fillStyle="#FFFFFF";0<n.find(function(m){return m.h}).C&&(k.font="50px Tahoma",y("\u2622",.07*x,v*(.45-.032)));.6<b?(Yb="Nominal",Vb=!1):.4<b?(Yb="Satisfactory",Vb=!1):.3<b?(Yb="Low",Vb=!1,Ub=0):15>=
F&&10<F?(Yb="Very Low",Vb=!0,Ub+=Y/400):10>=F&&5<F?(Yb="Critical",Vb=!0,Ub+=Y/150):5>=F&&(Yb="Deadly",Vb=!0,Ub+=Y/50)}
function hc(a){var b=.85*x,d=.45*v;k.lineWidth=2;k.textAlign="start";k.textBaseline="alphabetic";k.font="15px Arial";switch(a.a.type){case "SOLAR":var h=Nb*Math.max(.25,Math.sin(W*Math.PI/180));if(a.h&&F<Mb)F=Math.min(Mb,F+Y/1E3*h);else{var e=mb(a).filter(function(p){return null!=p.a.b}).filter(function(p){return p.a.b!=p.a.H}),l=h/e.length*(Y/1E3);e.forEach(function(p){p.a.b=p.a.b+l>=p.a.H?p.a.H:p.a.b+l})}a.h&&!S&&(y("\u26a1",b,d+20),Va(b,d+40+.08*v,.1*v,Math.min(1,h/Nb)));break;case "CONSTRUCTOR":null!=
a.a.D&&a.a.P&&(a.a.u+=Y/1E4*Ob,1<=a.a.u&&(Rb?(bb(a.a.D.product),a.a.D=null,playerTile.a.u=0):a.a.L=!0,a.a.P=!1));a.h&&!S&&(y("Recipe: "+(void 0!=a.a.D?a.a.D.product:"None"),b,d),y("\u26a1",b,d+20),a.a.L&&(k.fillStyle="#00FF00"),y("%",b+12+.025*v,d+20),Va(b,d+40+.08*v,.1*v,a.a.b/a.a.H),Va(10+b+.025*v,d+40+.08*v,.1*v,a.a.u));break;case "MINER":a.a.S?(a.a.u+=Y/1E4*Pb,1<=a.a.u&&(a.a.s+=1,a.a.S=!1,a.a.u=0,a.counter+=1),10==a.counter&&(Ya(a),a.counter=0)):1<=a.a.b&&"NONE"!=a.i.type&&a.a.s<a.a.U&&(--a.a.b,
a.a.S=!0);Qb&&(a.a.s-=ib(a.a.N,a.a.s));a.h&&!S&&(y("\u26a1",b,d+20),y("%",12+b+.025*v,d+20),y("\u2a06",24+b+.05*v,d+20),Va(b,d+40+.08*v,.1*v,Math.min(1,a.a.b/a.a.H)),Va(10+b+.025*v,d+40+.08*v,.1*v,a.a.u),Va(20+b+.05*v,d+40+.08*v,.1*v,a.a.s/a.a.U));break;case "RTG":a.h&&F<Mb?F=Math.min(Mb,F+Y/1E3*Sb):(e=mb(a).filter(function(p){return null!=p.a.b}).filter(function(p){return p.a.b!=p.a.H}),l=Sb/e.length*(Y/1E3),e.forEach(function(p){p.a.b=p.a.b+l>=p.a.H?p.a.H:p.a.b+l}))}}
document.addEventListener("keydown",function(a){switch(a.keyCode){case 87:H.g=!0;break;case 83:H.f=!0;break;case 68:H.right=!0;break;case 65:H.left=!0;break;case 69:H.c=!0;break;case 32:H.c=!0;break;case 66:H.F=!0;break;case 82:H.remove=!0;break;case 27:H.v=!0;break;case 16:H.I=!0}});
document.addEventListener("keyup",function(a){switch(a.keyCode){case 87:H.g=!1;break;case 83:H.f=!1;break;case 68:H.right=!1;break;case 65:H.left=!1;break;case 69:H.c=!1;break;case 32:H.c=!1;break;case 66:H.F=!1;break;case 82:H.remove=!1;break;case 27:H.v=!1;break;case 16:H.I=!1}});
setInterval(function(){Y=S?0:(new Date).getTime()-Ra;k.fillStyle="#000000";k.fillRect(0,0,Ja.clientWidth,Ja.clientHeight);ub&&dc();if(cc){k.strokeStyle="#FFFFFF";k.fillStyle="#000000AA";lb(.02,.9,.1);var a=.13*x,b=.11*v;k.font="22px Arial";k.fillStyle="#FFFFFF";k.strokeStyle="#000000";k.textAlign="start";k.textBaseline="alphabetic";y("Welcome, valued Roboemployee, to the JMC\u2122 Autonomous Mining Initative.",a,b);y("Over the course of the next 7 solar rotations your mining effectiveness will be assesed by",
a,50+b);y("your ability to meet daily monetary quotas.",a,75+b);y("Quotas can be met by ",a,100+b);var d=k.measureText("Quotas can be met by ").width;k.fillStyle="#00FF00";y("Mining (E/Space)",a+d,100+b);d+=k.measureText("Mining (E/Space)").width;k.fillStyle="#FFFFFF";y(" and selling resources to the TELEDEPOT.",a+d,100+b);y("Failure to complete these quotas will result in immediate nuclear vapourisation.",a,150+b);y("JMC\u2122 Operations & Managment regrets to inform you that terrain maps",a,200+
b);y("for JMC\u2122 Planet 404 have been lost, you are required to use your",a,225+b);y("JMC\u2122 Craft's ",a,250+b);d=k.measureText("JMC\u2122 Craft's ").width;k.fillStyle="#00FF00";y("Build (B) & Remove (R)",a+d,250+b);d+=k.measureText("Build (B) & Remove (R)").width;k.fillStyle="#FFFFFF";y(" functionality to place RADARs and uncover more terrain.",a+d,250+b);y("The CONSTRUCTOR creates buildings, such as extra RADARs, from resources and energy.",a,300+b);y("Your JMC\u2122 Craft has a limited battery capacity, failure to charge the battery",
a,325+b);y("will result in loss of resources and buildings in possesion.",a,350+b);y("An RTG has been made available to provide energy and charge your JMC\u2122 Craft.",a,375+b);y("A ROBOSHOP has been made available for you to purchase upgrades to aid effectiveness.",a,400+b);k.textAlign="center";y("WASD to move, left shift to sprint, E/Space to interact.",x/2,450+b);y("Good Luck.",x/2,.82*v);y("Press E/Space to start",x/2,25+.85*v);1==H.c&&0==G.c&&(cc=!1,bc=!0)}bc&&gc();G=Object.assign({},H);Ra=
(new Date).getTime()},50);